# Generated by Django 5.2.6 on 2026-02-11 02:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0017_accountingsettings_auto_create_job_costing_journal_and_more'),
        ('core', '0029_userprofile'),
        ('partners', '0013_alter_partner_address_alter_partner_address_line1_and_more'),
        ('sales', '0070_salesconfig_service_order_signature_source_and_more'),
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_no', models.CharField(blank=True, max_length=30, unique=True)),
                ('receipt_date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('pph_withheld', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted')], default='draft', max_length=10)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cash_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='partners.customer')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='sales.invoice')),
                ('journal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipt', to='accounting.journal')),
            ],
            options={
                'db_table': 'customer_receipts',
                'ordering': ['-receipt_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='VendorPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vb_number', models.CharField(blank=True, default='', max_length=30, unique=True)),
                ('letter_number', models.CharField(blank=True, default='', max_length=30, unique=True)),
                ('payment_date', models.DateField(default=django.utils.timezone.localdate)),
                ('idr_rate', models.DecimalField(decimal_places=6, default=1, max_digits=18)),
                ('reference', models.CharField(blank=True, default='', max_length=80)),
                ('memo', models.TextField(blank=True, default='')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('status', models.CharField(default='DRAFT', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cash_account', models.ForeignKey(help_text='Kas/Bank yang dipakai bayar', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.currency')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_payments', to='partners.vendor')),
            ],
            options={
                'db_table': 'vendor_payments',
            },
        ),
        migrations.CreateModel(
            name='VendorPaymentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='', max_length=180)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='payments.vendorpayment')),
                ('vendor_bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='shipments.vendorbill')),
            ],
            options={
                'db_table': 'vendor_payment_lines',
            },
        ),
    ]
