# Generated by Django 5.2.6 on 2025-12-25 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='pph_withheld',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
