# Generated by Django 5.2.6 on 2026-01-17 11:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0017_accountingsettings_auto_create_job_costing_journal_and_more'),
        ('core', '0027_coresetting_text_value'),
        ('partners', '0012_vendor'),
        ('payments', '0002_receipt_pph_withheld'),
        ('sales', '0064_alter_invoice_job_order'),
        ('shipments', '0027_remove_vendorbookingline_job_cost_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Receipt',
            new_name='CustomerReceipt',
        ),
        migrations.AlterModelTable(
            name='customerreceipt',
            table='customer_receipts',
        ),
        migrations.CreateModel(
            name='VendorPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vb_number', models.CharField(blank=True, default='', max_length=30, unique=True)),
                ('letter_number', models.CharField(blank=True, default='', max_length=30, unique=True)),
                ('payment_date', models.DateField(default=django.utils.timezone.localdate)),
                ('idr_rate', models.DecimalField(decimal_places=6, default=1, max_digits=18)),
                ('reference', models.CharField(blank=True, default='', max_length=80)),
                ('memo', models.TextField(blank=True, default='')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('status', models.CharField(default='DRAFT', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cash_account', models.ForeignKey(help_text='Kas/Bank yang dipakai bayar', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.currency')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_payments', to='partners.partner')),
            ],
            options={
                'db_table': 'vendor_payments',
            },
        ),
        migrations.CreateModel(
            name='VendorPaymentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='', max_length=180)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='payments.vendorpayment')),
                ('vendor_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='shipments.vendorbooking')),
            ],
        ),
    ]
