# Generated by Django 5.2.6 on 2026-01-25 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0013_alter_partner_address_alter_partner_address_line1_and_more'),
        ('payments', '0003_rename_receipt_customerreceipt_and_more'),
        ('shipments', '0042_vendorbill_vendorbillline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorpaymentline',
            name='vendor_booking',
        ),
        migrations.AddField(
            model_name='vendorpaymentline',
            name='vendor_bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='shipments.vendorbill'),
        ),
        migrations.AlterField(
            model_name='vendorpayment',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_payments', to='partners.vendor'),
        ),
    ]
