# Generated by Django 5.2.6 on 2026-02-26 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0017_accountingsettings_auto_create_job_costing_journal_and_more'),
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150)),
                ('company_address', models.TextField(blank=True)),
                ('company_phone', models.CharField(blank=True, max_length=50)),
                ('company_email', models.EmailField(blank=True, max_length=254)),
                ('company_npwp', models.CharField(blank=True, max_length=50)),
                ('invoice_title_default', models.CharField(default='INVOICE', max_length=100)),
                ('dp_invoice_title', models.CharField(default='DOWN PAYMENT INVOICE', max_length=100)),
                ('final_invoice_title', models.CharField(default='FINAL INVOICE', max_length=100)),
                ('default_customer_note', models.TextField(blank=True)),
                ('default_terms_conditions', models.TextField(blank=True)),
                ('default_footer_note', models.TextField(blank=True)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('bank_account_name', models.CharField(blank=True, max_length=150)),
                ('bank_account_number', models.CharField(blank=True, max_length=100)),
                ('swift_code', models.CharField(blank=True, max_length=50)),
                ('bank_address', models.TextField(blank=True)),
                ('signature_name', models.CharField(blank=True, max_length=150)),
                ('signature_title', models.CharField(blank=True, max_length=150)),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='billing/signatures/')),
                ('auto_show_signature', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Billing Configuration',
                'db_table': 'billing_config',
            },
        ),
        migrations.RemoveConstraint(
            model_name='invoice',
            name='unique_dp_per_job',
        ),
        migrations.AddField(
            model_name='billingconfig',
            name='receipt_journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.journal'),
        ),
        migrations.AddField(
            model_name='billingconfig',
            name='sales_journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.journal'),
        ),
        migrations.AddField(
            model_name='billingconfig',
            name='vendor_bill_journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.journal'),
        ),
        migrations.AddField(
            model_name='billingconfig',
            name='vendor_payment_journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.journal'),
        ),
    ]
