# Generated by Django 5.2.6 on 2026-02-26 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_billingconfig_remove_invoice_unique_dp_per_job_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingconfig',
            name='auto_show_signature',
        ),
        migrations.AddField(
            model_name='billingconfig',
            name='signature_mode',
            field=models.CharField(choices=[('MANUAL', 'Manual Upload'), ('USER', 'From System User')], default='MANUAL', max_length=10),
        ),
        migrations.AddField(
            model_name='billingconfig',
            name='signature_user',
            field=models.ForeignKey(blank=True, help_text='Select user to use their profile signature.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
