# Generated by Django 5.2.6 on 2026-02-26 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_remove_billingconfig_auto_show_signature_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingconfig',
            name='company_address',
        ),
        migrations.RemoveField(
            model_name='billingconfig',
            name='company_email',
        ),
        migrations.RemoveField(
            model_name='billingconfig',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='billingconfig',
            name='company_npwp',
        ),
        migrations.RemoveField(
            model_name='billingconfig',
            name='company_phone',
        ),
        migrations.RemoveField(
            model_name='billingconfig',
            name='receipt_journal',
        ),
        migrations.RemoveField(
            model_name='billingconfig',
            name='sales_journal',
        ),
        migrations.RemoveField(
            model_name='billingconfig',
            name='vendor_bill_journal',
        ),
        migrations.RemoveField(
            model_name='billingconfig',
            name='vendor_payment_journal',
        ),
    ]
