# Generated by Django 5.2.6 on 2026-02-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_remove_billingconfig_company_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='customer_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Customer Notes'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='terms_conditions',
            field=models.TextField(blank=True, null=True, verbose_name='Terms & Conditions'),
        ),
    ]
