# Generated by Django 5.2.6 on 2026-02-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_invoice_customer_notes_invoice_terms_conditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='tax_locked',
            field=models.BooleanField(default=False),
        ),
    ]
