# Generated by Django 5.2.6 on 2026-02-26 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_invoice_tax_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='idr_rate',
            field=models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=18, null=True),
        ),
    ]
