# Generated by Django 5.2.6 on 2025-10-28 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ref_number',
            field=models.CharField(default='TEMP', max_length=50, unique=True),
        ),
    ]
