# Generated by Django 5.2.6 on 2025-10-28 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_ref_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='ref_number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
