# Generated by Django 5.2.6 on 2025-10-28 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_ref_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='number',
            field=models.CharField(default='temp', max_length=50, unique=True),
        ),
    ]
