# Generated by Django 5.2.6 on 2025-10-29 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcost',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='projects/costs/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='projectcost',
            name='ref',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='number',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='ref_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['number'], name='projects_number_8bbb1b_idx'),
        ),
    ]
