# Generated by Django 5.2.6 on 2025-11-11 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_projectcost_attachment_projectcost_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='value_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='project',
            name='value_currency_code',
            field=models.CharField(default='IDR', max_length=3),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed'), ('ON_PROGRESS', 'On Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('ON_HOLD', 'On Hold')], default='DRAFT', max_length=20),
        ),
    ]
