# Generated by Django 5.2.6 on 2025-09-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_label', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50)),
                ('prefix', models.CharField(blank=True, default='', max_length=30)),
                ('period_format', models.CharField(choices=[('NONE', 'None'), ('YYYY', 'YYYY'), ('YYYYMM', 'YYYYMM'), ('MMYY', 'MMYY')], default='MMYY', max_length=10)),
                ('padding', models.PositiveIntegerField(default=4)),
                ('period_year', models.PositiveIntegerField(default=0)),
                ('period_month', models.PositiveIntegerField(default=0)),
                ('last_no', models.PositiveIntegerField(default=0)),
                ('branch', models.CharField(blank=True, default='', max_length=10)),
                ('mode', models.CharField(blank=True, default='', max_length=10)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'core_number_sequences',
                'unique_together': {('app_label', 'code', 'branch', 'mode')},
            },
        ),
    ]
