# Generated by Django 5.2.6 on 2025-10-20 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service',
            new_name='SalesService',
        ),
        migrations.AlterModelTable(
            name='numbersequence',
            table='core_number_sequences',
        ),
        migrations.AlterModelTable(
            name='paymentterm',
            table='payment_terms',
        ),
        migrations.AlterModelTable(
            name='salesservice',
            table='sales_services',
        ),
        migrations.AlterModelTable(
            name='uom',
            table='uom',
        ),
    ]
