# Generated by Django 5.2.6 on 2025-10-20 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_service_salesservice_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='currency',
            table='currencies',
        ),
    ]
