# Generated by Django 5.2.6 on 2025-10-20 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_currency_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='uom',
            table='uoms',
        ),
    ]
