# Generated by Django 5.2.6 on 2025-10-21 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_uom_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='numbersequence',
            old_name='last_no',
            new_name='last_number',
        ),
    ]
