# Generated by Django 5.2.6 on 2025-10-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_last_no_numbersequence_last_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('int_value', models.IntegerField(blank=True, null=True)),
                ('char_value', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'core_settings',
            },
        ),
    ]
