# Generated by Django 5.2.6 on 2025-10-25 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_companyprofile'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='numbersequence',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='numbersequence',
            name='format',
            field=models.CharField(default='{prefix}{year:04d}{month:02d}-{seq:05d}', help_text='Gunakan var: prefix, year, month, day (opsional), seq', max_length=120),
        ),
        migrations.AddField(
            model_name='numbersequence',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='numbersequence',
            name='reset',
            field=models.CharField(choices=[('none', 'None'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=10),
        ),
        migrations.AlterField(
            model_name='numbersequence',
            name='padding',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='numbersequence',
            name='period_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='numbersequence',
            name='period_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='numbersequence',
            name='prefix',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddIndex(
            model_name='numbersequence',
            index=models.Index(fields=['app_label', 'code'], name='core_number_app_lab_f5e3ec_idx'),
        ),
        migrations.AddConstraint(
            model_name='numbersequence',
            constraint=models.UniqueConstraint(fields=('app_label', 'code'), name='uniq_sequence_per_app_code'),
        ),
        migrations.AlterModelTable(
            name='numbersequence',
            table=None,
        ),
        migrations.RemoveField(
            model_name='numbersequence',
            name='active',
        ),
        migrations.RemoveField(
            model_name='numbersequence',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='numbersequence',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='numbersequence',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='numbersequence',
            name='period_format',
        ),
        migrations.RemoveField(
            model_name='numbersequence',
            name='updated_at',
        ),
    ]
