# Generated by Django 5.2.6 on 2025-10-25 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_numbersequence_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='numbersequence',
            new_name='core_number_app_lab_9c97e4_idx',
            old_name='core_number_app_lab_f5e3ec_idx',
        ),
        migrations.AlterModelTable(
            name='numbersequence',
            table='core_number_sequences',
        ),
    ]
