# Generated by Django 5.2.6 on 2025-12-07 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='group',
            new_name='service_group',
        ),
    ]
