# Generated by Django 5.2.6 on 2025-12-07 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_group_service_service_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_group',
            field=models.CharField(max_length=30),
        ),
    ]
