# Generated by Django 5.2.6 on 2025-12-15 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_taxcategory_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax',
            name='code',
            field=models.CharField(default='ppn_old', max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
