# Generated by Django 5.2.6 on 2025-12-27 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_companyprofile_created_at_and_more'),
        ('geo', '0007_location_altitude_location_country_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='address',
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='address_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='address_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='geo.location'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='geo.location'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='enable_auto_journal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='enable_job_cost',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='geo.location'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='regency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='geo.location'),
        ),
    ]
