# Generated by Django 5.2.6 on 2025-12-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_setupstate"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            # ✅ Jangan sentuh database (DB sudah sesuai, kolom completed_at/created_at sudah tidak ada)
            database_operations=[],
            # ✅ Rapikan STATE Django agar match dengan model sekarang
            state_operations=[
                migrations.RemoveField(
                    model_name="setupstate",
                    name="completed_at",
                ),
                migrations.RemoveField(
                    model_name="setupstate",
                    name="created_at",
                ),
                migrations.AddField(
                    model_name="setupstate",
                    name="setup_token",
                    field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
                ),
                migrations.AlterField(
                    model_name="setupstate",
                    name="current_step",
                    field=models.PositiveIntegerField(default=1),
                ),
                migrations.AlterField(
                    model_name="setupstate",
                    name="updated_at",
                    field=models.DateTimeField(blank=True, null=True),
                ),
            ],
        )
    ]
