# Generated by Django 5.2.6 on 2025-12-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_setupstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='setupstate',
            name='force_password_change',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='setupstate',
            name='initial_admin_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='setupstate',
            name='initial_admin_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='setupstate',
            name='initial_admin_username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
