# Generated by Django 5.2.6 on 2025-12-28 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_setupstate_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='country',
            field=models.CharField(blank=True, default='Indonesia', max_length=100),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='district',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='province',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='regency',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
