# Generated by Django 5.2.6 on 2025-12-29 19:06

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_accountingsettings_default_pph_account'),
        ('core', '0021_alter_service_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax',
            name='input_account',
            field=models.ForeignKey(blank=True, help_text='Account untuk pajak masukan (Purchase Tax Receivable).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='tax',
            name='is_withholding',
            field=models.BooleanField(default=False, help_text='Centang jika tax ini withholding (mis: PPh).'),
        ),
        migrations.AddField(
            model_name='tax',
            name='output_account',
            field=models.ForeignKey(blank=True, help_text='Account untuk pajak keluaran (Sales Tax Payable).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='tax',
            name='usage',
            field=models.CharField(choices=[('sales', 'Sales'), ('purchase', 'Purchase'), ('both', 'Sales & Purchase')], default='sales', max_length=10),
        ),
        migrations.AlterField(
            model_name='tax',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
    ]
