# Generated by Django 5.2.6 on 2026-01-04 15:33

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_tax_input_account_tax_is_withholding_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_date', models.DateField(db_index=True)),
                ('rate_to_idr', models.DecimalField(decimal_places=6, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))])),
                ('source', models.CharField(blank=True, default='MANUAL', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.currency')),
            ],
            options={
                'db_table': 'core_exchange_rates',
                'indexes': [models.Index(fields=['currency', 'rate_date'], name='core_exchan_currenc_cde177_idx')],
                'unique_together': {('currency', 'rate_date')},
            },
        ),
    ]
