# Generated by Django 5.2.6 on 2026-01-04 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_exchangerate'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='taxes',
            field=models.ManyToManyField(blank=True, help_text='Default taxes untuk invoice line yang memakai service ini.', related_name='services', to='core.tax'),
        ),
    ]
