# Generated by Django 5.2.6 on 2026-01-06 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_service_taxes'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentterm',
            name='dp_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Down Payment (%) misal 20.00. Kosongkan jika tidak ada DP.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='paymentterm',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='paymentterm',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentterm',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='exchangerate',
            constraint=models.UniqueConstraint(fields=('rate_date', 'currency'), name='uq_rate_date_currency'),
        ),
    ]
