# Generated by Django 5.2.6 on 2026-01-06 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_paymentterm_dp_percent_paymentterm_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coresetting',
            name='category',
            field=models.CharField(choices=[('sales', 'Sales'), ('finance', 'Finance'), ('operation', 'Operation')], db_index=True, default='sales', max_length=20),
        ),
    ]
