# Generated by Django 5.2.6 on 2026-01-06 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_coresetting_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='coresetting',
            name='text_value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
