# Generated by Django 5.2.6 on 2026-02-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_coresetting_text_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax',
            name='group',
            field=models.CharField(choices=[('PPN', 'PPN'), ('PPH', 'PPH'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=16),
        ),
    ]
