# Generated by Django 5.2.6 on 2026-02-06 23:02

import core.models.user_profile
import core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_tax_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('signature', models.ImageField(blank=True, null=True, upload_to=core.models.user_profile.signature_upload_path, validators=[core.validators.validate_image_extension, core.validators.validate_image_mime, core.validators.FileSizeValidator(1), core.validators.ImageDimensionsValidator(1200, 600)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
