# Generated by Django 5.2.1 on 2025-09-17 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('email', models.CharField(blank=True, max_length=120, null=True)),
                ('phone', models.CharField(blank=True, max_length=60, null=True)),
                ('tax', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('postcode', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'partners',
                'indexes': [models.Index(fields=['name'], name='partners_name_idx')],
            },
        ),
        migrations.CreateModel(
            name='PartnerRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(max_length=30)),
                ('partner', models.ForeignKey(db_column='partner_id', on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='partners.partner')),
            ],
            options={
                'db_table': 'partner_roles',
                'indexes': [models.Index(fields=['partner', 'role'], name='partner_role_idx')],
                'unique_together': {('partner', 'role')},
            },
        ),
    ]
