# Generated by Django 5.2.6 on 2025-10-20 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerRoleTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Partner Role Types',
                'verbose_name_plural': 'Partner Roles Type',
                'db_table': 'partner_role_types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.CharField(blank=True, max_length=120, null=True)),
                ('phone', models.CharField(blank=True, max_length=60, null=True)),
                ('mobile', models.CharField(blank=True, max_length=30, null=True)),
                ('websites', models.JSONField(blank=True, help_text='Daftar URL (list of strings). Kosongkan jika tidak ada.', null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Company Name')),
                ('company_type', models.CharField(blank=True, choices=[('PT', 'PT'), ('CV', 'CV'), ('UD', 'UD'), ('UKM', 'UKM')], max_length=10, null=True, verbose_name='Company Type')),
                ('is_individual', models.BooleanField(default=False, help_text='Centang jika perorangan; kosongkan jika perusahaan.')),
                ('is_pkp', models.BooleanField(default=False, help_text='Centang jika PKP (Pengusaha Kena Pajak).')),
                ('tax', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('post_code', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sales_user', models.ForeignKey(blank=True, db_column='sales_user_id', help_text='PIC sales/AM yang bertanggung jawab.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partners', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'partners',
            },
        ),
        migrations.CreateModel(
            name='PartnerRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_roles', to='partners.partner')),
                ('role_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_roles', to='partners.partnerroletypes')),
            ],
            options={
                'verbose_name': 'Partner Role',
                'verbose_name_plural': 'Partner Roles',
                'db_table': 'partner_roles',
            },
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['name'], name='partners_name_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='partnerrole',
            unique_together={('partner', 'role_type')},
        ),
    ]
