# Generated by Django 5.2.6 on 2025-10-13 03:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='is_individual',
            field=models.BooleanField(default=False, help_text='Centang jika perorangan; kosongkan jika perusahaan.'),
        ),
        migrations.AddField(
            model_name='partner',
            name='is_pkp',
            field=models.BooleanField(default=False, help_text='Centang jika PKP (Pengusaha Kena Pajak).'),
        ),
        migrations.AddField(
            model_name='partner',
            name='mobile',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='sales_user',
            field=models.ForeignKey(blank=True, db_column='sales_user_id', help_text='PIC sales/AM yang bertanggung jawab.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partner',
            name='websites',
            field=models.JSONField(blank=True, help_text='Daftar URL (list of strings). Kosongkan jika tidak ada.', null=True),
        ),
    ]
