# Generated by Django 5.2.6 on 2025-11-08 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='websites',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
