# Generated by Django 5.2.6 on 2025-10-13 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_partner_is_individual_partner_is_pkp_partner_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Company Name'),
        ),
        migrations.AddField(
            model_name='partner',
            name='company_type',
            field=models.CharField(blank=True, choices=[('PT', 'PT'), ('CV', 'CV'), ('UD', 'UD'), ('UKM', 'UKM')], max_length=10, null=True, verbose_name='Company Type'),
        ),
    ]
