# Generated by Django 5.2.6 on 2025-11-16 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0007_location_altitude_location_country_code_and_more'),
        ('partners', '0002_alter_partner_company_name_alter_partner_websites'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='address_line1',
            field=models.CharField(blank=True, help_text='Jalan, nomor rumah, komplek, gedung.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='address_line2',
            field=models.CharField(blank=True, help_text='RT/RW, blok, lantai, atau info tambahan lain.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='location',
            field=models.ForeignKey(blank=True, db_column='location_id', help_text='Pilih lokasi administrasi (kelurahan/kecamatan/kota) jika diketahui.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partners', to='geo.location'),
        ),
        migrations.AddField(
            model_name='partner',
            name='roles',
            field=models.ManyToManyField(blank=True, help_text='Peran partner (Customer, Vendor, Carrier, Agent, dll).', related_name='partners', through='partners.PartnerRole', to='partners.partnerroletypes'),
        ),
    ]
