# Generated by Django 5.2.6 on 2025-11-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_partner_address_line1_partner_address_line2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='job_title',
            field=models.CharField(blank=True, help_text='Jabatan contact utama, misal: Direktur, Owner, Procurement.', max_length=100, null=True, verbose_name='Job Title'),
        ),
    ]
