# Generated by Django 5.2.6 on 2025-11-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_partner_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='district_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kecamatan (teks bebas)'),
        ),
        migrations.AddField(
            model_name='partner',
            name='province_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Provinsi (teks bebas)'),
        ),
        migrations.AddField(
            model_name='partner',
            name='region_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kab/Kota (teks bebas)'),
        ),
        migrations.AddField(
            model_name='partner',
            name='village_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kelurahan/Desa (teks bebas)'),
        ),
    ]
