# Generated by Django 5.2.6 on 2025-11-18 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0007_location_altitude_location_country_code_and_more'),
        ('partners', '0005_partner_district_name_partner_province_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='district_name',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='province_name',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='region_name',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='village_name',
        ),
        migrations.AddField(
            model_name='partner',
            name='district',
            field=models.ForeignKey(blank=True, db_column='district_id', limit_choices_to={'kind': 'district'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partners_district', to='geo.location'),
        ),
        migrations.AddField(
            model_name='partner',
            name='province',
            field=models.ForeignKey(blank=True, db_column='province_id', limit_choices_to={'kind': 'province'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partners_province', to='geo.location'),
        ),
        migrations.AddField(
            model_name='partner',
            name='regency',
            field=models.ForeignKey(blank=True, db_column='regency_id', limit_choices_to={'kind': 'regency'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partners_regency', to='geo.location'),
        ),
        migrations.AddField(
            model_name='partner',
            name='village',
            field=models.ForeignKey(blank=True, db_column='village_id', limit_choices_to={'kind': 'village'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partners_village', to='geo.location'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='tax',
            field=models.CharField(blank=True, help_text='NPWP perusahaan / perorangan.', max_length=50, null=True, verbose_name='NPWP'),
        ),
    ]
