# Generated by Django 5.2.6 on 2025-11-18 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0006_remove_partner_district_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='company',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_individual': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='partners.partner'),
        ),
    ]
