# Generated by Django 5.2.6 on 2025-12-08 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0007_partner_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('partners.partner',),
        ),
    ]
