# Generated by Django 5.2.6 on 2025-12-12 10:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0008_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AddField(
            model_name='partner',
            name='bank_account',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='partner',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
