# Generated by Django 5.2.6 on 2025-12-13 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0009_partner_balance_partner_bank_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='is_billing_contact',
            field=models.BooleanField(default=False, help_text='Centang jika contact ini dipakai untuk Invoice / Billing.'),
        ),
        migrations.AddField(
            model_name='partner',
            name='is_sales_contact',
            field=models.BooleanField(default=False, help_text='Centang jika contact ini dipakai untuk Quotation / Sales Order.'),
        ),
    ]
