# Generated by Django 5.2.6 on 2025-12-13 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0010_partner_is_billing_contact_partner_is_sales_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='bank_account_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
