# Generated by Django 5.2.6 on 2025-12-28 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0011_partner_bank_account_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('partners.partner',),
        ),
    ]
