# Generated by Django 5.2.6 on 2026-01-20 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0012_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='partner',
            name='address_line1',
            field=models.CharField(blank=True, default='', help_text='Jalan, nomor rumah, komplek, gedung.', max_length=200),
        ),
        migrations.AlterField(
            model_name='partner',
            name='address_line2',
            field=models.CharField(blank=True, default='', help_text='RT/RW, blok, lantai, atau info tambahan lain.', max_length=200),
        ),
        migrations.AlterField(
            model_name='partner',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='partner',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='company_type',
            field=models.CharField(blank=True, choices=[('PT', 'PT'), ('CV', 'CV'), ('UD', 'UD'), ('UKM', 'UKM')], default='', max_length=10, verbose_name='Company Type'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='partner',
            name='email',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='partner',
            name='job_title',
            field=models.CharField(blank=True, default='', help_text='Jabatan contact utama, misal: Direktur, Owner, Procurement.', max_length=100, verbose_name='Job Title'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='mobile',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='partner',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='partner',
            name='post_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='partner',
            name='tax',
            field=models.CharField(blank=True, default='', help_text='NPWP perusahaan / perorangan.', max_length=50, verbose_name='NPWP'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='websites',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='partnerroletypes',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
