# Generated by Django 5.2.6 on 2026-02-11 02:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import django_summernote.fields
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0029_userprofile'),
        ('job', '0037_alter_joborder_customer_note_and_more'),
        ('partners', '0013_alter_partner_address_alter_partner_address_line1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('REJECTED', 'Rejected'), ('APPROVED', 'Approved'), ('SENT', 'Sent to Vendor'), ('CANCELLED', 'Cancelled'), ('CONFIRMED', 'Confirmed'), ('DONE', 'Done'), ('CLOSED', 'Closed')], default='DRAFT', max_length=20)),
                ('booking_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('reject_reason', models.TextField(blank=True, default='')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('sent_via', models.CharField(blank=True, default='', max_length=20)),
                ('sent_to', models.CharField(blank=True, default='', max_length=255)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.TextField(blank=True, default='')),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('vb_number', models.CharField(blank=True, default='', max_length=50)),
                ('idr_rate', models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=18, null=True)),
                ('wht_rate', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=9, validators=[django.core.validators.MinValueValidator(0)])),
                ('wht_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('subtotal_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('header_json', models.JSONField(blank=True, default=dict)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor_note', django_summernote.fields.SummernoteTextField(blank=True, default='', help_text='Catatan untuk vendor (Service Order)')),
                ('term_conditions', django_summernote.fields.SummernoteTextField(blank=True, default='', help_text='Syarat & ketentuan Service Order')),
                ('service_order_mode', models.CharField(choices=[('GENERAL', 'General'), ('SEA', 'Sea'), ('AIR', 'Air'), ('INLAND', 'Inland')], db_index=True, default='GENERAL', help_text='Mode Service Order untuk generate dokumen lanjutan', max_length=20)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.currency')),
                ('done_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('job_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_bookings', to='job.joborder')),
                ('payment_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.paymentterm')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='partners.vendor')),
            ],
            options={
                'db_table': 'vendor_bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceOrderAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='service_orders/%Y/%m/', verbose_name='File')),
                ('description', models.CharField(blank=True, help_text='Misal: Quotation Vendor, Booking Confirmation, dll.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_order_attachments', to=settings.AUTH_USER_MODEL)),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='work_orders.vendorbooking', verbose_name='Service Order Attachment')),
            ],
            options={
                'verbose_name': 'Service Order Attachment',
                'verbose_name_plural': 'Service Order Attachments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorBookingLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('qty', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=18)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('uom_code', models.CharField(blank=True, default='', max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('cost_group', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cost_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='job.jobcosttype')),
                ('job_cost', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='job.jobcost')),
                ('taxes', models.ManyToManyField(blank=True, related_name='vendor_booking_lines', to='core.tax')),
                ('uom', models.ForeignKey(blank=True, help_text='Default UOM untuk cost line (mis: LS, TRIP, CNTR, CBM, KG)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vb_line_uoms', to='core.uom')),
                ('vendor_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='work_orders.vendorbooking')),
            ],
            options={
                'db_table': 'vendor_booking_lines',
                'ordering': ['vendor_booking_id', 'id'],
            },
        ),
    ]
