# Generated by Django 5.2.6 on 2026-02-10 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorbooking',
            name='service_order_mode',
            field=models.CharField(choices=[('GENERAL', 'General'), ('SEA', 'Sea'), ('AIR', 'Air'), ('INLAND', 'Inland')], db_index=True, default='GENERAL', help_text='Mode Service Order untuk generate dokumen lanjutan', max_length=20),
        ),
        migrations.AddField(
            model_name='vendorbooking',
            name='term_conditions',
            field=models.TextField(blank=True, default='', help_text='Syarat & ketentuan Service Order'),
        ),
        migrations.AddField(
            model_name='vendorbooking',
            name='vendor_note',
            field=models.TextField(blank=True, default='', help_text='Catatan untuk vendor (Service Order)'),
        ),
    ]
