# Generated by Django 5.2.6 on 2026-02-10 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0002_vendorbooking_service_order_mode_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrderAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='service_orders/%Y/%m/', verbose_name='File')),
                ('description', models.CharField(blank=True, help_text='Misal: Quotation Vendor, Booking Confirmation, dll.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='work_orders.vendorbooking', verbose_name='Service Order Attachment')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_order_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service Order Attachment',
                'verbose_name_plural': 'Service Order Attachments',
                'ordering': ['-created_at'],
            },
        ),
    ]
