# Generated by Django 5.2.6 on 2026-02-10 12:02

import django_summernote.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0004_vendorbooking_done_at_vendorbooking_done_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorbooking',
            name='term_conditions',
            field=django_summernote.fields.SummernoteTextField(blank=True, default='', help_text='Syarat & ketentuan Service Order'),
        ),
        migrations.AlterField(
            model_name='vendorbooking',
            name='vendor_note',
            field=django_summernote.fields.SummernoteTextField(blank=True, default='', help_text='Catatan untuk vendor (Service Order)'),
        ),
    ]
