# Generated by Django 5.2.6 on 2025-11-09 14:20

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0009_rename_core_number_app_lab_f5e3ec_idx_core_number_app_lab_9c97e4_idx_and_more'),
        ('partners', '0002_alter_partner_company_name_alter_partner_websites'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True)),
                ('ref_number', models.CharField(blank=True, max_length=50, null=True)),
                ('order_date', models.DateField(default=django.utils.timezone.localdate)),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tax_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('subtotal_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed'), ('ON_PROGRESS', 'On Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('ON_HOLD', 'On Hold')], default='DRAFT', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='purchases/po/%Y/%m/')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='core.currency')),
                ('purchase_user', models.ForeignKey(blank=True, db_column='purchase_user_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(limit_choices_to={'role__code': 'vendor'}, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='partners.partnerrole')),
            ],
            options={
                'db_table': 'purchases_orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line_no', models.PositiveIntegerField(default=1)),
                ('product_name', models.CharField(blank=True, max_length=200)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('qty', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('line_discount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchases.purchaseorder')),
                ('uom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.uom')),
            ],
            options={
                'db_table': 'purchases_order_lines',
                'ordering': ['purchase_order_id', 'line_no'],
            },
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['number'], name='purchases_o_number_81a85d_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['order_date'], name='purchases_o_order_d_aeacfb_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['status'], name='purchases_o_status_6ca1b4_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['vendor'], name='purchases_o_vendor__392933_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='purchaseorderline',
            unique_together={('purchase_order', 'line_no')},
        ),
    ]
