# Generated by Django 5.2.6 on 2025-12-30 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0012_vendor'),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='vendor',
            field=models.ForeignKey(limit_choices_to={'role_type__code': 'vendor'}, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='partners.partnerrole'),
        ),
    ]
