# Generated by Django 5.2.6 on 2026-02-11 02:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0029_userprofile'),
        ('geo', '0007_location_altitude_location_country_code_and_more'),
        ('job', '0037_alter_joborder_customer_note_and_more'),
        ('partners', '0013_alter_partner_address_alter_partner_address_line1_and_more'),
        ('work_orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('POD', 'Proof of Delivery')], max_length=24)),
                ('file', models.FileField(blank=True, null=True, upload_to='shipment_docs/%Y/%m/')),
                ('is_public', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'shipments_documents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShipmentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yymm', models.CharField(max_length=4, unique=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_number', models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True)),
                ('tracking_no', models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PICKUP', 'Pickup'), ('IN_TRANSIT', 'In Transit'), ('OUT_FOR_DELIVERY', 'Out For Delivery'), ('DELIVERED', 'Delivered'), ('EXCEPTION', 'Exception'), ('CANCELED', 'Canceled')], db_index=True, default='DRAFT', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments_created', to=settings.AUTH_USER_MODEL)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments_destination', to='geo.location')),
                ('destination_airport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipments_destination_airport', to='geo.location')),
                ('destination_port', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipments_destination_port', to='geo.location')),
                ('job_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='job.joborder')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments_origin', to='geo.location')),
                ('origin_airport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipments_origin_airport', to='geo.location')),
                ('origin_port', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipments_origin_port', to='geo.location')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipments_services', to='core.service')),
            ],
            options={
                'db_table': 'shipments_shipment',
            },
        ),
        migrations.CreateModel(
            name='ShipmentLeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField()),
                ('mode', models.CharField(choices=[('TRUCK', 'Truck'), ('SEA', 'Sea'), ('AIR', 'Air')], max_length=16)),
                ('planned_departure', models.DateTimeField(blank=True, null=True)),
                ('planned_arrival', models.DateTimeField(blank=True, null=True)),
                ('actual_departure', models.DateTimeField(blank=True, null=True)),
                ('actual_arrival', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('EXCEPTION', 'Exception'), ('CANCELED', 'Canceled')], db_index=True, default='PLANNED', max_length=16)),
                ('from_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legs_from', to='geo.location')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='shipments.shipment')),
                ('to_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legs_to', to='geo.location')),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentLegTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField()),
                ('truck_size', models.CharField(blank=True, max_length=32, null=True)),
                ('vehicle_type', models.CharField(blank=True, max_length=32, null=True)),
                ('driver_name', models.CharField(blank=True, max_length=128, null=True)),
                ('plate_no', models.CharField(blank=True, max_length=32, null=True)),
                ('planned_pickup', models.DateTimeField(blank=True, null=True)),
                ('planned_dropoff', models.DateTimeField(blank=True, null=True)),
                ('actual_pickup', models.DateTimeField(blank=True, null=True)),
                ('actual_dropoff', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('DISPATCHED', 'Dispatched'), ('PICKED_UP', 'Picked Up'), ('IN_TRANSIT', 'In Transit'), ('ARRIVED', 'Arrived'), ('COMPLETED', 'Completed'), ('EXCEPTION', 'Exception'), ('CANCELED', 'Canceled')], db_index=True, default='PLANNED', max_length=16)),
                ('leg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='shipments.shipmentleg')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partners.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('SHIPMENT_CREATED', 'Shipment Created'), ('PICKUP_SCHEDULED', 'Pickup Scheduled'), ('PICKUP_DISPATCHED', 'Pickup Dispatched'), ('PICKUP_COMPLETED', 'Pickup Completed'), ('DEPARTED', 'Departed'), ('ARRIVED', 'Arrived'), ('OUTFORDELIVERY', 'Outfordelivery'), ('DELIVERED', 'Delivered'), ('POD_UPLOADED', 'Pod Uploaded'), ('EXCEPTION', 'Exception'), ('EXCEPTION_RESOLVED', 'Exception Resolved'), ('CANCELED', 'Canceled')], db_index=True, max_length=64)),
                ('event_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('location_text', models.CharField(blank=True, max_length=255, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('is_public', models.BooleanField(db_index=True, default=False)),
                ('affects_status', models.BooleanField(default=True)),
                ('dedupe_key', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(default='OPS', max_length=32)),
                ('source_ref', models.CharField(blank=True, max_length=64, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='shipments.shipment')),
                ('leg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='shipments.shipmentleg')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='shipments.shipmentlegtrip')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingInstructionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_type', models.CharField(choices=[('SEA_SI', 'Sea Shipping Instruction')], default='SEA_SI', max_length=20)),
                ('sequence_no', models.PositiveIntegerField()),
                ('document_no', models.CharField(max_length=30, unique=True)),
                ('letter_date', models.DateField(default=django.utils.timezone.localdate)),
                ('shipper_name', models.CharField(max_length=255)),
                ('shipper_address', models.TextField(blank=True)),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('customer_address', models.TextField(blank=True)),
                ('reference_no', models.CharField(blank=True, max_length=50)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('job_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_order_documents', to='job.joborder')),
                ('vendor_booking', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipping_instruction', to='work_orders.vendorbooking')),
            ],
        ),
        migrations.CreateModel(
            name='SeaShippingInstructionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier_name', models.CharField(blank=True, max_length=255)),
                ('vessel_name', models.CharField(blank=True, max_length=255)),
                ('voyage_no', models.CharField(blank=True, max_length=50)),
                ('pol', models.CharField(blank=True, max_length=255)),
                ('pod', models.CharField(blank=True, max_length=255)),
                ('final_destination', models.CharField(blank=True, max_length=255)),
                ('etd', models.DateField(blank=True, null=True)),
                ('eta', models.DateField(blank=True, null=True)),
                ('special_instructions', models.TextField(blank=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sea_detail', to='shipments.shippinginstructiondocument')),
            ],
        ),
        migrations.CreateModel(
            name='VendorBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(max_length=40, unique=True)),
                ('bill_date', models.DateField(default=django.utils.timezone.localdate)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('idr_rate', models.DecimalField(decimal_places=6, default=1, max_digits=18)),
                ('reference', models.CharField(blank=True, default='', max_length=80)),
                ('notes', models.TextField(blank=True, default='')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('status', models.CharField(default='DRAFT', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.currency')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_bills', to='partners.partner')),
            ],
            options={
                'db_table': 'vendor_bills',
            },
        ),
        migrations.CreateModel(
            name='VendorBillLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='', max_length=180)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='shipments.vendorbill')),
                ('taxes', models.ManyToManyField(blank=True, related_name='vendor_bill_lines', to='core.tax')),
                ('vendor_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='work_orders.vendorbooking')),
            ],
            options={
                'db_table': 'vendor_bill_lines',
            },
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['status'], name='shipments_s_status_536511_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['created_at'], name='shipments_s_created_1bef45_idx'),
        ),
        migrations.AddIndex(
            model_name='shipmentleg',
            index=models.Index(fields=['shipment', 'status'], name='shipments_s_shipmen_8315c5_idx'),
        ),
        migrations.AddConstraint(
            model_name='shipmentleg',
            constraint=models.UniqueConstraint(fields=('shipment', 'seq'), name='uq_leg_shipment_seq'),
        ),
        migrations.AddIndex(
            model_name='shipmentlegtrip',
            index=models.Index(fields=['leg', 'status'], name='shipments_s_leg_id_d82d7e_idx'),
        ),
        migrations.AddConstraint(
            model_name='shipmentlegtrip',
            constraint=models.UniqueConstraint(fields=('leg', 'seq'), name='uq_trip_leg_seq'),
        ),
        migrations.AddIndex(
            model_name='shipmentevent',
            index=models.Index(fields=['shipment', 'event_time'], name='shipments_s_shipmen_289a4a_idx'),
        ),
        migrations.AddIndex(
            model_name='shipmentevent',
            index=models.Index(fields=['shipment', 'is_public', 'event_time'], name='shipments_s_shipmen_317970_idx'),
        ),
        migrations.AddConstraint(
            model_name='shippinginstructiondocument',
            constraint=models.UniqueConstraint(fields=('letter_type', 'sequence_no'), name='uniq_doc_sequence_per_letter_type'),
        ),
    ]
