# Generated by Django 5.2.6 on 2025-09-24 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
        ('partners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('transportation_mode', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'transportation_types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30)),
                ('cargo_description', models.TextField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('volume', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('etd', models.DateField(blank=True, null=True)),
                ('eta', models.DateField(blank=True, null=True)),
                ('atd', models.DateTimeField(blank=True, null=True)),
                ('ata', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'DRAFT'), ('BOOKED', 'BOOKED'), ('IN_TRANSIT', 'IN_TRANSIT'), ('DELIVERED', 'DELIVERED'), ('CANCELLED', 'CANCELLED')], default='DRAFT', max_length=20)),
                ('is_multimodal', models.BooleanField(db_column='is_multimoda', default=False)),
                ('origin_text', models.CharField(blank=True, db_column='origin', max_length=100, null=True)),
                ('destination_text', models.CharField(blank=True, db_column='destination', max_length=100, null=True)),
                ('bill_of_lading_no', models.CharField(blank=True, max_length=50, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(blank=True, db_column='agency_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_agency_shipments', to='partners.partner')),
                ('carrier', models.ForeignKey(blank=True, db_column='carrier_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_carrier_shipments', to='partners.partner')),
                ('consignee', models.ForeignKey(blank=True, db_column='consignee_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_consignee_shipments', to='partners.partner')),
                ('destination', models.ForeignKey(db_column='destination_id', on_delete=django.db.models.deletion.PROTECT, related_name='shipment_destinations', to='geo.location')),
                ('origin', models.ForeignKey(db_column='origin_id', on_delete=django.db.models.deletion.PROTECT, related_name='shipment_origins', to='geo.location')),
                ('shipper', models.ForeignKey(blank=True, db_column='shipper_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_shipper_shipments', to='partners.partner')),
            ],
            options={
                'db_table': 'shipments',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(max_length=50)),
                ('file_path', models.CharField(db_column='file_path', max_length=255)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='shipments.shipment')),
            ],
            options={
                'db_table': 'shipment_documents',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'DRAFT'), ('BOOKED', 'BOOKED'), ('IN_TRANSIT', 'IN_TRANSIT'), ('DELIVERED', 'DELIVERED'), ('CANCELLED', 'CANCELLED')], max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('event_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='shipments.shipment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipment_status_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shipment_status_logs',
            },
        ),
        migrations.CreateModel(
            name='ShipmentRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(db_column='destination_id', on_delete=django.db.models.deletion.PROTECT, related_name='route_destinations', to='geo.location')),
                ('origin', models.ForeignKey(db_column='origin_id', on_delete=django.db.models.deletion.PROTECT, related_name='route_origins', to='geo.location')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='shipments.shipment')),
                ('transportation_type', models.ForeignKey(db_column='transportation_type_id', on_delete=django.db.models.deletion.RESTRICT, to='shipments.transportationtype')),
            ],
            options={
                'db_table': 'shipment_routes',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['number'], name='shipments_number_e1f820_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['status'], name='shipments_status_cda325_idx'),
        ),
        migrations.AddIndex(
            model_name='shipmentstatuslog',
            index=models.Index(fields=['shipment', 'event_time'], name='shipment_st_shipmen_b58bc6_idx'),
        ),
        migrations.AddIndex(
            model_name='shipmentstatuslog',
            index=models.Index(fields=['status'], name='shipment_st_status_1b14c9_idx'),
        ),
    ]
