# Generated by Django 5.2.6 on 2025-09-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=6, unique=True)),
                ('last_no', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'shipment_number_sequences',
            },
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'DRAFT'), ('BOOKED', 'BOOKED'), ('IN_TRANSIT', 'IN_TRANSIT'), ('DELIVERED', 'DELIVERED'), ('CANCELLED', 'CANCELLED')], db_index=True, default='DRAFT', max_length=20),
        ),
    ]
