# Generated by Django 5.2.6 on 2025-10-26 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0003_alter_location_code'),
        ('partners', '0001_initial'),
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportationAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(db_index=True, max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='ShipmentNumberSequence',
        ),
        migrations.RemoveField(
            model_name='shipmentstatuslog',
            name='shipment',
        ),
        migrations.RemoveField(
            model_name='shipmentstatuslog',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='shipmentroute',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='transportationtype',
            options={},
        ),
        migrations.RemoveField(
            model_name='transportationtype',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='transportationtype',
            name='transportation_mode',
        ),
        migrations.RemoveField(
            model_name='transportationtype',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='shipment',
            name='agency_snap',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='airwaybill_no',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='booking_number',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name='shipment',
            name='carrier_snap',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='consignee_snap',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='currency',
            field=models.CharField(blank=True, default='IDR', max_length=10),
        ),
        migrations.AddField(
            model_name='shipment',
            name='customer_reference',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='shipment',
            name='destination_snap',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='flight_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='shipment',
            name='inco_term',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='shipment',
            name='mode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='shipment',
            name='notify_party',
            field=models.ForeignKey(blank=True, db_column='notify_party_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_notify_shipments', to='partners.partner'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='origin_snap',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='package_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='shipment',
            name='service_level',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipper_snap',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='so_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='vessel_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='shipment',
            name='voyage_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='shipmentroute',
            name='actual_arrival',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipmentroute',
            name='actual_departure',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipmentroute',
            name='carrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes_as_carrier', to='partners.partner'),
        ),
        migrations.AddField(
            model_name='shipmentroute',
            name='destination_snap',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipmentroute',
            name='destination_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='shipmentroute',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='shipmentroute',
            name='notes',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='shipmentroute',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Urutan rute dalam shipment'),
        ),
        migrations.AddField(
            model_name='shipmentroute',
            name='origin_snap',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipmentroute',
            name='origin_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='shipmentroute',
            name='planned_arrival',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='shipmentroute',
            name='planned_departure',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='shipmentroute',
            name='status',
            field=models.CharField(choices=[('PLANNED', 'Planned'), ('IN_TRANSIT', 'In Transit'), ('ARRIVED', 'Arrived'), ('DELAYED', 'Delayed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PLANNED', max_length=12),
        ),
        migrations.AddField(
            model_name='shipmentroute',
            name='transportation_asset_snap',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipmentroute',
            name='transportation_asset_text',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='shipmentroute',
            name='transportation_type_snap',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipmentroute',
            name='transportation_type_text',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='transportationtype',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='transportationtype',
            name='mode',
            field=models.CharField(blank=True, choices=[('SEA', 'Sea'), ('LAND', 'Land'), ('AIR', 'Air'), ('RAIL', 'Rail')], db_index=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='transportationtype',
            name='notes',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='bill_of_lading_no',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='number',
            field=models.CharField(db_index=True, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('BOOKED', 'Booked'), ('IN_TRANSIT', 'In Transit'), ('ARRIVED', 'Arrived'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='shipmentroute',
            name='transportation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shipments.transportationtype'),
        ),
        migrations.AlterField(
            model_name='transportationtype',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['booking_number'], name='shipments_booking_c77fcd_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['bill_of_lading_no'], name='shipments_bill_of_0019c9_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['airwaybill_no'], name='shipments_airwayb_f16887_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['origin'], name='shipments_origin__c5eeb7_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['destination'], name='shipments_destina_4650cb_idx'),
        ),
        migrations.AddConstraint(
            model_name='shipment',
            constraint=models.CheckConstraint(condition=models.Q(('origin', models.F('destination')), _negated=True), name='ck_shipment_origin_not_eq_dest'),
        ),
        migrations.AlterModelTable(
            name='transportationtype',
            table=None,
        ),
        migrations.AddField(
            model_name='transportationasset',
            name='carrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partners.partner'),
        ),
        migrations.AddField(
            model_name='transportationasset',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='shipments.transportationtype'),
        ),
        migrations.AddField(
            model_name='shipmentroute',
            name='transportation_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shipments.transportationasset'),
        ),
        migrations.AddIndex(
            model_name='shipmentroute',
            index=models.Index(fields=['shipment', 'order'], name='shipment_ro_shipmen_c2b189_idx'),
        ),
        migrations.AddIndex(
            model_name='shipmentroute',
            index=models.Index(fields=['status'], name='shipment_ro_status_559367_idx'),
        ),
        migrations.AddIndex(
            model_name='shipmentroute',
            index=models.Index(fields=['planned_departure'], name='shipment_ro_planned_9e161e_idx'),
        ),
        migrations.AddIndex(
            model_name='shipmentroute',
            index=models.Index(fields=['planned_arrival'], name='shipment_ro_planned_89d375_idx'),
        ),
        migrations.AddConstraint(
            model_name='shipmentroute',
            constraint=models.UniqueConstraint(fields=('shipment', 'order'), name='uq_shipment_route_order'),
        ),
        migrations.AddConstraint(
            model_name='shipmentroute',
            constraint=models.CheckConstraint(condition=models.Q(('origin', models.F('destination')), _negated=True), name='ck_route_origin_not_eq_dest'),
        ),
        migrations.DeleteModel(
            name='ShipmentStatusLog',
        ),
    ]
