# Generated by Django 5.2.6 on 2026-02-11 08:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0037_alter_joborder_customer_note_and_more'),
        ('shipments', '0002_remove_shippinginstructiondocument_letter_type_and_more'),
        ('work_orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        
    ]
