# Generated by Django 5.2.6 on 2025-10-26 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0003_alter_shipment_options_shipment_booked_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='shipments/%Y/%m/')),
                ('label', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='shipments.shipment')),
            ],
            options={
                'permissions': [],
            },
        ),
    ]
