# Generated by Django 5.2.6 on 2026-02-11 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0003_remove_shippinginstructiondocument_uniq_doc_sequence_per_letter_type_and_more'),
    ]

    operations = [
        
    ]
