# Generated by Django 5.2.6 on 2025-10-26 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_salesquotation_sales_service'),
        ('shipments', '0004_shipmentattachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='customer_reference',
        ),
        migrations.AddField(
            model_name='shipment',
            name='sales_order',
            field=models.ForeignKey(blank=True, db_column='sales_order_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='sales.salesorder'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='sales_order_snap',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
