# Generated by Django 5.2.6 on 2026-02-26 02:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0044_alter_joborder_job_source'),
        ('shipments', '0004_remove_shippinginstructiondocument_uniq_doc_sequence'),
        ('work_orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='shippinginstructiondocument',
            name='uniq_doc_sequence',
        ),
        migrations.AddConstraint(
            model_name='shippinginstructiondocument',
            constraint=models.UniqueConstraint(fields=('sequence_no',), name='uniq_si_sequence_no'),
        ),
    ]
