# Generated by Django 5.2.6 on 2025-10-28 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0005_remove_shipment_customer_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='driver_info',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
