# Generated by Django 5.2.6 on 2026-02-26 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
       
        ('shipments', '0005_remove_shippinginstructiondocument_uniq_doc_sequence_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorbillline',
            name='bill',
        ),
        migrations.RemoveField(
            model_name='vendorbillline',
            name='taxes',
        ),
        migrations.RemoveField(
            model_name='vendorbillline',
            name='vendor_booking',
        ),
        migrations.DeleteModel(
            name='VendorBill',
        ),
        migrations.DeleteModel(
            name='VendorBillLine',
        ),
    ]
