# Generated by Django 5.2.6 on 2025-10-28 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0006_shipment_driver_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='driver_info',
        ),
        migrations.AddField(
            model_name='shipmentroute',
            name='driver_info',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
