# Generated by Django 5.2.6 on 2025-11-11 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_core_number_app_lab_f5e3ec_idx_core_number_app_lab_9c97e4_idx_and_more'),
        ('shipments', '0007_remove_shipment_driver_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='sales_service',
            field=models.ForeignKey(blank=True, db_column='sales_service_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipmen_services', to='core.salesservice'),
        ),
    ]
