# Generated by Django 5.2.6 on 2025-11-11 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_alter_partner_company_name_alter_partner_websites'),
        ('shipments', '0009_alter_shipment_sales_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='customer',
            field=models.ForeignKey(blank=True, db_column='customer_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_customer_shipments', to='partners.partner'),
        ),
    ]
