# Generated by Django 5.2.6 on 2026-01-07 04:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_coresetting_text_value'),
        ('geo', '0007_location_altitude_location_country_code_and_more'),
        ('job', '0007_joborder_complete_journal_alter_jobcost_cost_type'),
        ('partners', '0012_vendor'),
        ('shipments', '0010_shipment_customer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, unique=True)),
                ('booking_date', models.DateField()),
                ('origin_text', models.CharField(max_length=255)),
                ('destination_text', models.CharField(max_length=255)),
                ('etd', models.DateField(blank=True, null=True)),
                ('eta', models.DateField(blank=True, null=True)),
                ('source_type', models.CharField(choices=[('quotation', 'Quotation'), ('verbal', 'Verbal / Phone'), ('rate_card', 'Rate Card')], default='verbal', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_vendor_bookings', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.currency')),
                ('destination_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='geo.location')),
                ('origin_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='geo.location')),
                ('payment_term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.paymentterm')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.service')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_bookings', to='partners.partner')),
            ],
            options={
                'ordering': ['-booking_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='VendorBookingLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('qty', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('uom', models.CharField(default='LS', max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('expected_tax_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('expected_tax_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='shipments.vendorbooking')),
                ('cost_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='job.jobcosttype')),
                ('expected_tax', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.tax')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
