# Generated by Django 5.2.6 on 2026-01-07 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0007_location_altitude_location_country_code_and_more'),
        ('shipments', '0011_vendorbooking_vendorbookingline'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorbooking',
            name='delivery_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='vendorbooking',
            name='pickup_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='vendorbooking',
            name='destination_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='geo.location'),
        ),
        migrations.AlterField(
            model_name='vendorbooking',
            name='destination_text',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='vendorbooking',
            name='origin_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='geo.location'),
        ),
        migrations.AlterField(
            model_name='vendorbooking',
            name='origin_text',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='vendorbooking',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='vendorbookingline',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='vendorbookingline',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
