# Generated by Django 5.2.6 on 2026-01-07 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_coresetting_text_value'),
        ('shipments', '0012_vendorbooking_delivery_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorbookingline',
            name='expected_tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.tax'),
        ),
    ]
