# Generated by Django 5.2.6 on 2026-01-08 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0013_alter_vendorbookingline_expected_tax'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendorbookingline',
            old_name='expected_tax',
            new_name='estimated_tax',
        ),
        migrations.RenameField(
            model_name='vendorbookingline',
            old_name='expected_tax_amount',
            new_name='estimated_tax_amount',
        ),
        migrations.RenameField(
            model_name='vendorbookingline',
            old_name='expected_tax_rate',
            new_name='estimated_tax_rate',
        ),
    ]
