# Generated by Django 5.2.6 on 2026-01-09 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0012_vendor'),
        ('shipments', '0014_rename_expected_tax_vendorbookingline_estimated_tax_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorbooking',
            name='service',
        ),
        migrations.AddField(
            model_name='vendorbooking',
            name='is_transport',
            field=models.BooleanField(default=False, help_text='Booking transport = melibatkan pemindahan cargo.'),
        ),
        migrations.AlterField(
            model_name='vendorbooking',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='partners.vendor'),
        ),
    ]
