# Generated by Django 5.2.6 on 2026-01-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0015_remove_vendorbooking_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorbookingline',
            name='details',
            field=models.JSONField(blank=True, default=dict, help_text='Structured detail for this booking line (transport/doc/etc).'),
        ),
    ]
