# Generated by Django 5.2.6 on 2026-01-13 00:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_coresetting_text_value'),
        ('job', '0009_jobcosttype_accrued_liability_account_and_more'),
        ('partners', '0012_vendor'),
        ('shipments', '0016_vendorbookingline_details'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendorbooking',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='vendorbookingline',
            options={'ordering': ['booking_id', 'line_no']},
        ),
        migrations.RemoveField(
            model_name='vendorbooking',
            name='booking_date',
        ),
        migrations.RemoveField(
            model_name='vendorbooking',
            name='delivery_note',
        ),
        migrations.RemoveField(
            model_name='vendorbooking',
            name='destination_location',
        ),
        migrations.RemoveField(
            model_name='vendorbooking',
            name='destination_text',
        ),
        migrations.RemoveField(
            model_name='vendorbooking',
            name='eta',
        ),
        migrations.RemoveField(
            model_name='vendorbooking',
            name='etd',
        ),
        migrations.RemoveField(
            model_name='vendorbooking',
            name='is_transport',
        ),
        migrations.RemoveField(
            model_name='vendorbooking',
            name='number',
        ),
        migrations.RemoveField(
            model_name='vendorbooking',
            name='origin_location',
        ),
        migrations.RemoveField(
            model_name='vendorbooking',
            name='origin_text',
        ),
        migrations.RemoveField(
            model_name='vendorbooking',
            name='payment_term',
        ),
        migrations.RemoveField(
            model_name='vendorbooking',
            name='pickup_note',
        ),
        migrations.RemoveField(
            model_name='vendorbooking',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='vendorbooking',
            name='source_type',
        ),
        migrations.RemoveField(
            model_name='vendorbooking',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='vendorbookingline',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='vendorbookingline',
            name='estimated_tax',
        ),
        migrations.RemoveField(
            model_name='vendorbookingline',
            name='estimated_tax_amount',
        ),
        migrations.RemoveField(
            model_name='vendorbookingline',
            name='estimated_tax_rate',
        ),
        migrations.RemoveField(
            model_name='vendorbookingline',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='vendorbooking',
            name='booking_no',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='vendorbooking',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='vendorbooking',
            name='issued_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='vendorbookingline',
            name='description_is_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendorbookingline',
            name='line_no',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='vendorbookingline',
            name='service_type',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='vendorbookingline',
            name='source_job_cost',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendor_booking_line', to='job.jobcost'),
        ),
        migrations.AddField(
            model_name='vendorbookingline',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='vendorbooking',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vendorbooking',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.currency'),
        ),
        migrations.AlterField(
            model_name='vendorbooking',
            name='job_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_bookings', to='job.joborder'),
        ),
        migrations.AlterField(
            model_name='vendorbooking',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='vendorbooking',
            name='vendor',
            field=models.ForeignKey(blank=True, help_text='Vendor header untuk booking (wajib sebelum Confirm).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendor_bookings', to='partners.partner'),
        ),
        migrations.AlterField(
            model_name='vendorbookingline',
            name='cost_type',
            field=models.ForeignKey(blank=True, help_text='Jenis biaya/vendor work (master Cost Type). Dipilih dari modal.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='job.jobcosttype'),
        ),
        migrations.AlterField(
            model_name='vendorbookingline',
            name='details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='vendorbookingline',
            name='qty',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='vendorbookingline',
            name='uom',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterModelTable(
            name='vendorbooking',
            table='vendor_bookings',
        ),
    ]
