# Generated by Django 5.2.6 on 2026-01-13 04:43

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_coresetting_text_value'),
        ('partners', '0012_vendor'),
        ('shipments', '0017_alter_vendorbooking_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorbooking',
            name='exchange_rate',
        ),
        migrations.AddField(
            model_name='vendorbooking',
            name='idr_rate',
            field=models.DecimalField(blank=True, decimal_places=6, default=None, help_text='Rate currency ke IDR (1 currency = X IDR).', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='vendorbooking',
            name='payment_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.paymentterm'),
        ),
        migrations.AddField(
            model_name='vendorbooking',
            name='pph_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='PPh amount (currency header)', max_digits=18),
        ),
        migrations.AddField(
            model_name='vendorbooking',
            name='pph_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='PPh (%)', max_digits=6),
        ),
        migrations.AddField(
            model_name='vendorbooking',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AddField(
            model_name='vendorbooking',
            name='total_idr',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='vendorbooking',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='partners.vendor'),
        ),
    ]
