# Generated by Django 5.2.6 on 2026-01-13 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0018_remove_vendorbooking_exchange_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorbooking',
            name='pph_amount',
        ),
        migrations.RemoveField(
            model_name='vendorbooking',
            name='pph_rate',
        ),
    ]
