# Generated by Django 5.2.6 on 2026-01-13 06:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0019_remove_vendorbooking_pph_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorbooking',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
    ]
