# Generated by Django 5.2.6 on 2026-01-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0020_vendorbooking_discount_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorbooking',
            name='discount_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Informational only', max_digits=6, null=True),
        ),
    ]
