# Generated by Django 5.2.6 on 2026-01-13 09:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_coresetting_text_value'),
        ('shipments', '0021_vendorbooking_discount_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorbookingline',
            name='taxes',
            field=models.ManyToManyField(blank=True, related_name='booking_lines', to='core.tax'),
        ),
        migrations.AddField(
            model_name='vendorbookingline',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='vendorbookingline',
            name='qty',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=18),
        ),
    ]
