# Generated by Django 5.2.6 on 2026-01-15 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0022_vendorbookingline_taxes_vendorbookingline_unit_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorbooking',
            name='booking_group',
            field=models.CharField(choices=[('INLAND', 'Inland Transportation'), ('SEA', 'Sea Freight'), ('AIR', 'Air Freight'), ('PORT', 'Customs Clearance'), ('PACKING', 'Packing / Lashing'), ('DOCUMENT', 'Documentation'), ('WAREHOUSE', 'Warehouse'), ('OTHER', 'Other')], db_index=True, default='OTHER', help_text='Booking Type. Mengunci semua line dalam satu service group.', max_length=50),
            preserve_default=False,
        ),
    ]
