# Generated by Django 5.2.6 on 2026-01-16 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0023_vendorbooking_booking_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendorbooking',
            old_name='booking_no',
            new_name='vb_number',
        ),
        migrations.AddField(
            model_name='vendorbooking',
            name='header_json',
            field=models.JSONField(blank=True, default=dict, help_text='Flexible header data for SI / SLI / Trucking Order'),
        ),
        migrations.AddField(
            model_name='vendorbooking',
            name='letter_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
