# Generated by Django 5.2.6 on 2026-01-16 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0024_rename_booking_no_vendorbooking_vb_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorbooking',
            name='letter_type',
            field=models.CharField(choices=[('SEA_SI', 'Shipping Instruction (Sea)'), ('AIR_SLI', 'Shipping Letter of Instruction (Air)'), ('TRUCK_TO', 'Trucking Order')], default='TRUCK_TO', help_text='Jenis dokumen: Sea SI / Air SLI / Trucking Order', max_length=20),
        ),
        migrations.AlterField(
            model_name='vendorbooking',
            name='booking_group',
            field=models.CharField(choices=[('INLAND', 'Inland'), ('SEA', 'Sea Freight'), ('AIR', 'Air Freight'), ('PORT', 'Customs Clearance'), ('PACKING', 'Packing / Lashing'), ('DOCUMENT', 'Documentation'), ('WAREHOUSE', 'Warehouse'), ('OTHER', 'Other')], db_index=True, help_text='Booking Type. Mengunci semua line dalam satu service group.', max_length=50),
        ),
    ]
