# Generated by Django 5.2.6 on 2026-01-16 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0025_vendorbooking_letter_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendorbookingline',
            options={'ordering': ['vendor_booking_id', 'line_no']},
        ),
        migrations.RenameField(
            model_name='vendorbookingline',
            old_name='booking',
            new_name='vendor_booking',
        ),
        migrations.RemoveField(
            model_name='vendorbookingline',
            name='description_is_manual',
        ),
        migrations.RemoveField(
            model_name='vendorbookingline',
            name='service_type',
        ),
        migrations.RemoveField(
            model_name='vendorbookingline',
            name='source_job_cost',
        ),
        migrations.AddField(
            model_name='vendorbookingline',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='vendorbookingline',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vendorbookingline',
            name='job_cost_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorbookingline',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
