# Generated by Django 5.2.6 on 2026-01-17 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0013_remove_jobcost_category_jobcost_vb_allocated_qty_and_more'),
        ('shipments', '0026_alter_vendorbookingline_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorbookingline',
            name='job_cost_id',
        ),
        migrations.AddField(
            model_name='vendorbookingline',
            name='job_cost',
            field=models.ForeignKey(blank=True, help_text='Source Job Cost line (for allocation & locking).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='job.jobcost'),
        ),
        migrations.AlterField(
            model_name='vendorbookingline',
            name='cost_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='job.jobcosttype'),
        ),
    ]
