# Generated by Django 5.2.6 on 2026-01-17 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0027_remove_vendorbookingline_job_cost_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorbookingline',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
