# Generated by Django 5.2.6 on 2026-01-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0028_vendorbookingline_last_synced_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorbookingline',
            name='last_synced_at',
        ),
        migrations.AddField(
            model_name='vendorbooking',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
