# Generated by Django 5.2.6 on 2026-01-18 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0029_remove_vendorbookingline_last_synced_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorbookingline',
            name='cost_group',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
