# Generated by Django 5.2.6 on 2026-01-18 04:11

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0030_vendorbookingline_cost_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorbooking',
            name='subtotal_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Jumlah sebelum pajak & wht', max_digits=18, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='vendorbooking',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Jumlah pajak dari taxes di lines', max_digits=18, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='vendorbooking',
            name='wht_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Nilai PPh/WHT (auto dari rate x base)', max_digits=18, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='vendorbooking',
            name='wht_rate',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), help_text='PPh/WHT rate (%) dipotong dari pembayaran (mis: 2.0, 4.0)', max_digits=9, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
