# Generated by Django 5.2.6 on 2026-01-18 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0031_vendorbooking_subtotal_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorbookingline',
            name='vat_included',
            field=models.BooleanField(default=False),
        ),
    ]
