# Generated by Django 5.2.6 on 2026-01-22 08:53

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_coresetting_text_value'),
        ('job', '0015_alter_jobcost_uom'),
        ('shipments', '0032_vendorbookingline_vat_included'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendorbookingline',
            options={'ordering': ['vendor_booking_id', 'id']},
        ),
        migrations.RemoveField(
            model_name='vendorbooking',
            name='discount_rate',
        ),
        migrations.RemoveField(
            model_name='vendorbooking',
            name='last_synced_at',
        ),
        migrations.RemoveField(
            model_name='vendorbooking',
            name='total_idr',
        ),
        migrations.RemoveField(
            model_name='vendorbookingline',
            name='details',
        ),
        migrations.RemoveField(
            model_name='vendorbookingline',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='vendorbookingline',
            name='line_no',
        ),
        migrations.RemoveField(
            model_name='vendorbookingline',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='vendorbookingline',
            name='vat_included',
        ),
        migrations.AlterField(
            model_name='vendorbooking',
            name='booking_group',
            field=models.CharField(choices=[('INLAND', 'Inland'), ('SEA', 'Sea Freight'), ('AIR', 'Air Freight'), ('PORT', 'Customs Clearance'), ('PACKING', 'Packing / Lashing'), ('DOCUMENT', 'Documentation'), ('WAREHOUSE', 'Warehouse'), ('OTHER', 'Other')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='vendorbooking',
            name='header_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='vendorbooking',
            name='idr_rate',
            field=models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='vendorbooking',
            name='letter_type',
            field=models.CharField(choices=[('SEA_SI', 'Shipping Instruction (Sea)'), ('AIR_SLI', 'Shipping Letter of Instruction (Air)'), ('TRUCK_TO', 'Trucking Order')], default='TRUCK_TO', max_length=20),
        ),
        migrations.AlterField(
            model_name='vendorbooking',
            name='subtotal_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='vendorbooking',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='vendorbooking',
            name='wht_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='vendorbooking',
            name='wht_rate',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=9, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='vendorbookingline',
            name='job_cost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='job.jobcost'),
        ),
        migrations.AlterField(
            model_name='vendorbookingline',
            name='taxes',
            field=models.ManyToManyField(blank=True, related_name='vendor_booking_lines', to='core.tax'),
        ),
    ]
