# Generated by Django 5.2.6 on 2026-01-23 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0033_alter_vendorbookingline_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendorbookingline',
            old_name='uom',
            new_name='uom_code',
        ),
    ]
