# Generated by Django 5.2.6 on 2026-01-23 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_coresetting_text_value'),
        ('shipments', '0036_alter_vendorbookingline_uom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorbookingline',
            name='uom',
            field=models.ForeignKey(blank=True, help_text='Default UOM untuk cost line (mis: LS, TRIP, CNTR, CBM, KG)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vb_line_uoms', to='core.uom'),
        ),
    ]
