# Generated by Django 5.2.6 on 2026-01-24 11:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0022_add_jobcosttype_uom_id_db'),
        ('shipments', '0037_alter_vendorbookingline_uom'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingInstructionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_type', models.CharField(choices=[('SEA_SI', 'Sea Shipping Instruction')], default='SEA_SI', max_length=20)),
                ('sequence_no', models.PositiveIntegerField()),
                ('document_no', models.CharField(max_length=30, unique=True)),
                ('letter_date', models.DateField(default=django.utils.timezone.localdate)),
                ('shipper_name', models.CharField(max_length=255)),
                ('shipper_address', models.TextField(blank=True)),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('customer_address', models.TextField(blank=True)),
                ('reference_no', models.CharField(blank=True, max_length=50)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('job_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_order_documents', to='job.joborder')),
                ('vendor_booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_documents', to='shipments.vendorbooking')),
            ],
        ),
        migrations.CreateModel(
            name='SeaShippingInstructionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier_name', models.CharField(blank=True, max_length=255)),
                ('vessel_name', models.CharField(blank=True, max_length=255)),
                ('voyage_no', models.CharField(blank=True, max_length=50)),
                ('pol', models.CharField(blank=True, max_length=255)),
                ('pod', models.CharField(blank=True, max_length=255)),
                ('final_destination', models.CharField(blank=True, max_length=255)),
                ('etd', models.DateField(blank=True, null=True)),
                ('eta', models.DateField(blank=True, null=True)),
                ('special_instructions', models.TextField(blank=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sea_detail', to='shipments.shippinginstructiondocument')),
            ],
        ),
        migrations.AddConstraint(
            model_name='shippinginstructiondocument',
            constraint=models.UniqueConstraint(fields=('letter_type', 'sequence_no'), name='uniq_doc_sequence_per_letter_type'),
        ),
    ]
