# Generated by Django 5.2.6 on 2026-01-24 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0038_shippinginstructiondocument_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorbooking',
            name='booking_group',
        ),
        migrations.RemoveField(
            model_name='vendorbooking',
            name='issued_date',
        ),
        migrations.RemoveField(
            model_name='vendorbooking',
            name='letter_number',
        ),
        migrations.RemoveField(
            model_name='vendorbooking',
            name='letter_type',
        ),
    ]
