# Generated by Django 5.2.6 on 2026-01-24 13:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0039_remove_vendorbooking_booking_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorbooking',
            name='booking_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate),
        ),
    ]
