# Generated by Django 5.2.6 on 2026-01-25 21:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_coresetting_text_value'),
        ('partners', '0013_alter_partner_address_alter_partner_address_line1_and_more'),
        ('shipments', '0041_vendorbooking_approved_at_vendorbooking_approved_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(max_length=40, unique=True)),
                ('bill_date', models.DateField(default=django.utils.timezone.localdate)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('idr_rate', models.DecimalField(decimal_places=6, default=1, max_digits=18)),
                ('reference', models.CharField(blank=True, default='', max_length=80)),
                ('notes', models.TextField(blank=True, default='')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('status', models.CharField(default='DRAFT', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.currency')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_bills', to='partners.partner')),
            ],
            options={
                'db_table': 'vendor_bills',
            },
        ),
        migrations.CreateModel(
            name='VendorBillLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='', max_length=180)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='shipments.vendorbill')),
                ('vendor_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='shipments.vendorbooking')),
            ],
            options={
                'db_table': 'vendor_bill_lines',
            },
        ),
    ]
