# Generated by Django 5.2.6 on 2026-01-25 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_coresetting_text_value'),
        ('shipments', '0043_vendorbill_taxes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorbill',
            name='taxes',
        ),
        migrations.AddField(
            model_name='vendorbillline',
            name='taxes',
            field=models.ManyToManyField(blank=True, related_name='vendor_bill_lines', to='core.tax'),
        ),
    ]
