# Generated by Django 5.2.6 on 2026-02-01 10:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0007_location_altitude_location_country_code_and_more'),
        ('partners', '0013_alter_partner_address_alter_partner_address_line1_and_more'),
        ('shipments', '0044_remove_vendorbill_taxes_vendorbillline_taxes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yymm', models.CharField(max_length=4, unique=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='shipmentroute',
            name='carrier',
        ),
        migrations.RemoveField(
            model_name='shipmentroute',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='shipmentroute',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='shipmentroute',
            name='shipment',
        ),
        migrations.RemoveField(
            model_name='shipmentroute',
            name='transportation_asset',
        ),
        migrations.RemoveField(
            model_name='shipmentroute',
            name='transportation_type',
        ),
        migrations.RemoveField(
            model_name='transportationasset',
            name='carrier',
        ),
        migrations.RemoveField(
            model_name='transportationasset',
            name='type',
        ),
        migrations.AlterModelOptions(
            name='shipment',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='shipmentdocument',
            options={'managed': False},
        ),
        migrations.CreateModel(
            name='ShipmentLeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField()),
                ('mode', models.CharField(choices=[('TRUCK', 'Truck'), ('SEA', 'Sea'), ('AIR', 'Air')], max_length=16)),
                ('planned_departure', models.DateTimeField(blank=True, null=True)),
                ('planned_arrival', models.DateTimeField(blank=True, null=True)),
                ('actual_departure', models.DateTimeField(blank=True, null=True)),
                ('actual_arrival', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('EXCEPTION', 'Exception'), ('CANCELED', 'Canceled')], db_index=True, default='PLANNED', max_length=16)),
                ('from_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legs_from', to='geo.location')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='shipments.shipment')),
                ('to_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legs_to', to='geo.location')),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentLegTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField()),
                ('truck_size', models.CharField(blank=True, max_length=32, null=True)),
                ('vehicle_type', models.CharField(blank=True, max_length=32, null=True)),
                ('driver_name', models.CharField(blank=True, max_length=128, null=True)),
                ('plate_no', models.CharField(blank=True, max_length=32, null=True)),
                ('planned_pickup', models.DateTimeField(blank=True, null=True)),
                ('planned_dropoff', models.DateTimeField(blank=True, null=True)),
                ('actual_pickup', models.DateTimeField(blank=True, null=True)),
                ('actual_dropoff', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('DISPATCHED', 'Dispatched'), ('PICKED_UP', 'Picked Up'), ('IN_TRANSIT', 'In Transit'), ('ARRIVED', 'Arrived'), ('COMPLETED', 'Completed'), ('EXCEPTION', 'Exception'), ('CANCELED', 'Canceled')], db_index=True, default='PLANNED', max_length=16)),
                ('leg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='shipments.shipmentleg')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partners.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('SHIPMENT_CREATED', 'Shipment Created'), ('PICKUP_SCHEDULED', 'Pickup Scheduled'), ('PICKUP_DISPATCHED', 'Pickup Dispatched'), ('PICKUP_COMPLETED', 'Pickup Completed'), ('DEPARTED', 'Departed'), ('ARRIVED', 'Arrived'), ('OUTFORDELIVERY', 'Outfordelivery'), ('DELIVERED', 'Delivered'), ('POD_UPLOADED', 'Pod Uploaded'), ('EXCEPTION', 'Exception'), ('EXCEPTION_RESOLVED', 'Exception Resolved'), ('CANCELED', 'Canceled')], db_index=True, max_length=64)),
                ('event_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('location_text', models.CharField(blank=True, max_length=255, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('is_public', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(default='OPS', max_length=32)),
                ('source_ref', models.CharField(blank=True, max_length=64, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='shipments.shipment')),
                ('leg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='shipments.shipmentleg')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='shipments.shipmentlegtrip')),
            ],
        ),
        migrations.DeleteModel(
            name='ShipmentAttachment',
        ),
        migrations.DeleteModel(
            name='ShipmentRoute',
        ),
        migrations.DeleteModel(
            name='TransportationAsset',
        ),
        migrations.DeleteModel(
            name='TransportationType',
        ),
        migrations.AddIndex(
            model_name='shipmentleg',
            index=models.Index(fields=['shipment', 'status'], name='shipments_s_shipmen_8315c5_idx'),
        ),
        migrations.AddConstraint(
            model_name='shipmentleg',
            constraint=models.UniqueConstraint(fields=('shipment', 'seq'), name='uq_leg_shipment_seq'),
        ),
        migrations.AddIndex(
            model_name='shipmentlegtrip',
            index=models.Index(fields=['leg', 'status'], name='shipments_s_leg_id_d82d7e_idx'),
        ),
        migrations.AddConstraint(
            model_name='shipmentlegtrip',
            constraint=models.UniqueConstraint(fields=('leg', 'seq'), name='uq_trip_leg_seq'),
        ),
        migrations.AddIndex(
            model_name='shipmentevent',
            index=models.Index(fields=['shipment', 'event_time'], name='shipments_s_shipmen_289a4a_idx'),
        ),
        migrations.AddIndex(
            model_name='shipmentevent',
            index=models.Index(fields=['shipment', 'is_public', 'event_time'], name='shipments_s_shipmen_317970_idx'),
        ),
    ]
