# Generated by Django 5.2.6 on 2026-02-01 17:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0007_location_altitude_location_country_code_and_more'),
        ('partners', '0013_alter_partner_address_alter_partner_address_line1_and_more'),
        ('shipments', '0046_tracking_init'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipment',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='shipmentdocument',
            options={'managed': (False,)},
        ),
        migrations.AddField(
            model_name='shipmentevent',
            name='affects_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shipmentevent',
            name='dedupe_key',
            field=models.CharField(blank=True, db_index=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='shipmentdocument',
            name='doc_type',
            field=models.CharField(choices=[('POD', 'Proof of Delivery')], max_length=24),
        ),
        migrations.AlterField(
            model_name='shipmentdocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='shipment_docs/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='shipmentdocument',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='shipmentevent',
            name='code',
            field=models.CharField(choices=[('SHIPMENT_CREATED', 'Shipment Created'), ('PICKUP_SCHEDULED', 'Pickup Scheduled'), ('PICKUP_DISPATCHED', 'Pickup Dispatched'), ('PICKUP_COMPLETED', 'Pickup Completed'), ('DEPARTED', 'Departed'), ('ARRIVED', 'Arrived'), ('OUTFORDELIVERY', 'Outfordelivery'), ('DELIVERED', 'Delivered'), ('POD_UPLOADED', 'Pod Uploaded'), ('EXCEPTION', 'Exception'), ('EXCEPTION_RESOLVED', 'Exception Resolved'), ('CANCELED', 'Canceled')], db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='shipmentevent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='shipmentleg',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='shipmentlegtrip',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='shipmentsequence',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='shipmentdocument',
            index=models.Index(fields=['shipment', 'doc_type'], name='shipments_d_shipmen_c91aa3_idx'),
        ),
        migrations.AddIndex(
            model_name='shipmentdocument',
            index=models.Index(fields=['shipment', 'is_public'], name='shipments_d_shipmen_8a9b5f_idx'),
        ),
        migrations.AddIndex(
            model_name='shipmentevent',
            index=models.Index(fields=['shipment', 'event_time'], name='shipments_s_shipmen_289a4a_idx'),
        ),
        migrations.AddIndex(
            model_name='shipmentevent',
            index=models.Index(fields=['shipment', 'is_public', 'event_time'], name='shipments_s_shipmen_317970_idx'),
        ),
        migrations.AddIndex(
            model_name='shipmentleg',
            index=models.Index(fields=['shipment', 'status'], name='shipments_s_shipmen_8315c5_idx'),
        ),
        migrations.AddIndex(
            model_name='shipmentlegtrip',
            index=models.Index(fields=['leg', 'status'], name='shipments_s_leg_id_d82d7e_idx'),
        ),
        migrations.AlterModelTable(
            name='shipmentdocument',
            table='shipments_documents',
        ),
    ]
