# Generated by Django 5.2.6 on 2026-02-01 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0047_alter_shipment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='shipment',
            table='shipments_shipment',
        ),
    ]
