# Generated by Django 5.2.6 on 2026-02-02 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0050_sync_origin_airport_columns'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipmentdocument',
            options={'managed': False},
        ),
    ]
