# Generated by Django 5.2.6 on 2026-02-02 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0051_alter_shipmentdocument_options'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE shipments_shipment
                ADD COLUMN shipment_number VARCHAR(20) NULL;
            """,
            reverse_sql="""
                ALTER TABLE shipments_shipment
                DROP COLUMN shipment_number;
            """,
        ),
        migrations.RunSQL(
            sql="CREATE INDEX idx_shipments_shipment_number ON shipments_shipment (shipment_number);",
            reverse_sql="DROP INDEX idx_shipments_shipment_number ON shipments_shipment;",
        ),
    ]