# Generated by Django 5.2.6 on 2026-02-06 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0052_alter_shipmentdocument_shipment_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipment',
            options={},
        ),
    ]
