# Generated by Django 5.2.6 on 2026-02-09 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_userprofile'),
        ('geo', '0007_location_altitude_location_country_code_and_more'),
        ('job', '0036_joborder_term_conditions'),
        ('shipments', '0053_alter_shipment_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='shipment',
            new_name='shipments_s_created_1bef45_idx',
            old_name='shipments_created_at_idx',
        ),
        migrations.AddField(
            model_name='shipment',
            name='destination_airport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipments_destination_airport', to='geo.location'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='destination_port',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipments_destination_port', to='geo.location'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='origin_airport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipments_origin_airport', to='geo.location'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='origin_port',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipments_origin_port', to='geo.location'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipment_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments_destination', to='geo.location'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments_origin', to='geo.location'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipments_services', to='core.service'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['status'], name='shipments_s_status_536511_idx'),
        ),
    ]
