# Generated by Django 5.2.6 on 2026-02-09 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0054_rename_shipments_created_at_idx_shipments_s_created_1bef45_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorbooking',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='vendorbooking',
            name='cancelled_by',
        ),
        migrations.RemoveField(
            model_name='vendorbooking',
            name='closed_by',
        ),
        migrations.RemoveField(
            model_name='vendorbooking',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='vendorbooking',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='vendorbooking',
            name='job_order',
        ),
        migrations.RemoveField(
            model_name='vendorbooking',
            name='payment_term',
        ),
        migrations.RemoveField(
            model_name='vendorbooking',
            name='sent_by',
        ),
        migrations.RemoveField(
            model_name='vendorbooking',
            name='submitted_by',
        ),
        migrations.RemoveField(
            model_name='vendorbooking',
            name='vendor',
        ),
    ]
