# Generated by Django 5.2.6 on 2026-02-09 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0055_remove_vendorbooking_approved_by_and_more'),
        ('work_orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorbillline',
            name='vendor_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='work_orders.vendorbooking'),
        ),
        migrations.AlterField(
            model_name='shippinginstructiondocument',
            name='vendor_booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipping_instruction', to='work_orders.vendorbooking'),
        ),
        migrations.RemoveField(
            model_name='vendorbookingline',
            name='vendor_booking',
        ),
        migrations.RemoveField(
            model_name='vendorbookingline',
            name='cost_type',
        ),
        migrations.RemoveField(
            model_name='vendorbookingline',
            name='job_cost',
        ),
        migrations.RemoveField(
            model_name='vendorbookingline',
            name='taxes',
        ),
        migrations.RemoveField(
            model_name='vendorbookingline',
            name='uom',
        ),
        migrations.DeleteModel(
            name='VendorBooking',
        ),
        migrations.DeleteModel(
            name='VendorBookingLine',
        ),
    ]
