# Generated by Django 5.2.6 on 2025-12-15 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0014_tax_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesTaxPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('INVOICE', 'Invoice'), ('SO', 'Sales Order'), ('QUOTATION', 'Quotation')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('tax', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_policies', to='core.tax')),
            ],
            options={
                'ordering': ['module', 'tax__name'],
                'unique_together': {('module', 'tax')},
            },
        ),
    ]
