# Generated by Django 5.2.1 on 2025-09-17 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('kind', models.CharField(max_length=20)),
                ('lft', models.IntegerField(blank=True, null=True)),
                ('rght', models.IntegerField(blank=True, null=True)),
                ('iata_code', models.CharField(blank=True, max_length=10, null=True)),
                ('unlocode', models.CharField(blank=True, max_length=10, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('parent', models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='geo.location')),
            ],
            options={
                'db_table': 'locations',
                'indexes': [models.Index(fields=['code'], name='loc_code_idx'), models.Index(fields=['kind'], name='loc_kind_idx'), models.Index(fields=['parent'], name='loc_parent_idx')],
            },
        ),
    ]
