# Generated by Django 5.2.6 on 2025-10-20 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['name'], name='loc_name_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['iata_code'], name='loc_iata_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['unlocode'], name='loc_unlocode_idx'),
        ),
    ]
