# Generated by Django 5.2.6 on 2025-10-20 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_location_loc_name_idx_location_loc_iata_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
