# Generated by Django 5.2.6 on 2025-10-27 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0003_alter_location_code'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='location',
            name='loc_code_idx',
        ),
    ]
