# Generated by Django 5.2.6 on 2025-11-16 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0004_remove_location_loc_code_idx'),
    ]

    operations = [
     
    ]
