# Generated by Django 5.2.6 on 2025-11-16 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0005_location_altitude_location_country_code_and_more'),
    ]

    operations = [
       
    ]
