# Generated by Django 5.2.6 on 2025-12-24 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_account_is_postable_account_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='kind',
            field=models.CharField(choices=[('OPEN', 'Opening Balance'), ('GJ', 'General Journal')], default='GJ', max_length=10),
        ),
    ]
