# Generated by Django 5.2.6 on 2025-12-24 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_journal_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='test',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
