# Generated by Django 5.2.6 on 2025-12-24 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_journal_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='test',
        ),
        migrations.AddField(
            model_name='account',
            name='test',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
