# Generated by Django 5.2.6 on 2025-12-24 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_remove_journal_test_account_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='test',
        ),
    ]
