# Generated by Django 5.2.6 on 2025-12-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_accountingperiodlock'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_fiscal_year', models.PositiveIntegerField(default=2025)),
            ],
        ),
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['chart_year', 'code']},
        ),
        migrations.AddField(
            model_name='account',
            name='chart_year',
            field=models.PositiveIntegerField(db_index=True, default=2025),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('chart_year', 'code'), name='uniq_account_code_per_year'),
        ),
    ]
