# Generated by Django 5.2.6 on 2025-12-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_accountingsettings_alter_account_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingsettings',
            name='posting_policy',
            field=models.CharField(choices=[('open_if_missing', 'Allow posting if no period lock exists (missing = OPEN)'), ('strict_require', 'Allow posting only when period explicitly OPEN (missing = BLOCK)')], default='open_if_missing', max_length=32),
        ),
    ]
