# Generated by Django 5.2.6 on 2025-12-25 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_accountingsettings_posting_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingsettings',
            name='default_ar_account',
            field=models.ForeignKey(blank=True, help_text='Default Accounts Receivable for Sales Invoice', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='default_sales_account',
            field=models.ForeignKey(blank=True, help_text='Default Sales Revenue for Sales Invoice', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='default_tax_account',
            field=models.ForeignKey(blank=True, help_text='Default Output Tax Payable for Sales Invoice', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account'),
        ),
    ]
