# Generated by Django 5.2.6 on 2025-12-25 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_accountingsettings_default_ar_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingsettings',
            name='default_cash_account',
            field=models.ForeignKey(blank=True, help_text='Default Cash/Bank account for receipts/payments', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account'),
        ),
    ]
