# Generated by Django 5.2.6 on 2025-12-25 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_accountingsettings_default_cash_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingsettings',
            name='default_pph_account',
            field=models.ForeignKey(blank=True, help_text='Account for PPH withholding on customer receipts (PPH ikut payment)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account'),
        ),
    ]
