# Generated by Django 5.2.6 on 2026-01-02 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_accountingsettings_default_pph_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingsettings',
            name='auto_post_customer_receipt',
            field=models.BooleanField(default=False, help_text='Auto post journal Customer Receipt saat receipt POSTED/CONFIRMED.'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='auto_post_job_costing',
            field=models.BooleanField(default=False, help_text='Auto post journal Accrued COGS saat Job COMPLETED (accrual).'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='auto_post_sales_invoice',
            field=models.BooleanField(default=False, help_text='Auto post journal Sales saat Invoice ISSUED (accrual).'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='default_accrued_cogs_account',
            field=models.ForeignKey(blank=True, help_text='Default accrued liability untuk COGS accrual (credit) saat Job Completed.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account'),
        ),
        migrations.AlterField(
            model_name='accountingsettings',
            name='active_fiscal_year',
            field=models.PositiveIntegerField(default=2026),
        ),
    ]
