# Generated by Django 5.2.6 on 2026-01-03 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_accountingsettings_auto_post_customer_receipt_and_more'),
        ('core', '0022_tax_input_account_tax_is_withholding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.currency'),
        ),
        migrations.AddField(
            model_name='journal',
            name='source_ref',
            field=models.CharField(blank=True, db_index=True, help_text='Reference number of source document', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='source_type',
            field=models.CharField(blank=True, db_index=True, help_text='JOB, INV, PAY, etc', max_length=20, null=True),
        ),
    ]
