# Generated by Django 5.2.6 on 2026-01-03 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0014_journal_currency_journal_source_ref_and_more'),
        ('core', '0022_tax_input_account_tax_is_withholding_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='journal',
            index=models.Index(fields=['source_type', 'source_ref'], name='accounting__source__0fd9fd_idx'),
        ),
    ]
