# Generated by Django 5.2.6 on 2026-01-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0016_journal_created_by_journal_posted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingsettings',
            name='auto_create_job_costing_journal',
            field=models.BooleanField(default=True, help_text='Jika ON: saat Job Complete, sistem membuat draft journal COGS (accrual estimate).'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='auto_post_job_costing_journal',
            field=models.BooleanField(default=False, help_text='Jika ON: draft journal COGS langsung di-post (lock) saat Job Complete.'),
        ),
    ]
