# Generated by Django 5.2.6 on 2025-12-30 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0012_accountingsettings_default_pph_account'),
        ('core', '0022_tax_input_account_tax_is_withholding_and_more'),
        ('partners', '0012_vendor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCostType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('group', models.CharField(blank=True, default='', max_length=50)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accrued_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
                ('cogs_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
            ],
            options={
                'db_table': 'job_cost_types',
                'ordering': ['sort_order', 'group', 'name'],
            },
        ),
        migrations.CreateModel(
            name='JobOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=30, unique=True, verbose_name='Job No')),
                ('order_number', models.CharField(blank=True, help_text='Customer reference eg. PO#', max_length=30, null=True)),
                ('job_date', models.DateField(verbose_name='Date')),
                ('cargo_description', models.CharField(blank=True, help_text='Deskripsi singkat cargo.', max_length=255)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, help_text='Jumlah / volume cargo (opsional).', max_digits=10, null=True)),
                ('pickup', models.CharField(blank=True, help_text='Alamat / lokasi penjemputan.', max_length=255, verbose_name='Pick Up')),
                ('delivery', models.CharField(blank=True, help_text='Alamat / lokasi pengantaran.', max_length=255, verbose_name='Delivery')),
                ('pic', models.CharField(blank=True, help_text='Nama PIC.', max_length=100, verbose_name='PIC')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('is_tax', models.BooleanField(default=False, verbose_name='Apply Tax 1.1 (VAT)')),
                ('is_pph', models.BooleanField(default=False, verbose_name='Apply PPH')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('kurs_idr', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('total_in_idr', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pph_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('remarks_internal', models.TextField(blank=True, help_text='Catatan internal untuk tim.')),
                ('is_invoiced', models.BooleanField(default=False, help_text='Sudah dibuat invoice')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ON_GOING', 'On Going'), ('ON_HOLD', 'On Hold'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], db_index=True, default='DRAFT', max_length=20)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('hold_at', models.DateTimeField(blank=True, null=True)),
                ('hold_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='job_order_currency', to='core.currency')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_jobs', to='partners.customer', verbose_name='Customer')),
                ('payment_term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs_payments', to='core.paymentterm', verbose_name='Payment Term')),
                ('sales_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job_order_sales_user', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs_services', to='core.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'JobOrder',
                'verbose_name_plural': 'JobOrders',
                'db_table': 'job_orders',
                'ordering': ['-job_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='JobCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('est_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('actual_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.CharField(choices=[('VENDOR', 'Vendor Cost'), ('MOBILIZATION', 'Mobilization'), ('LABOUR', 'Labour'), ('DOCUMENT', 'Document'), ('MISC', 'Misc')], db_index=True, default='VENDOR', max_length=20)),
                ('internal_note', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='partners.vendor')),
                ('cost_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='job.jobcosttype')),
                ('job_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_order_costs', to='job.joborder')),
            ],
            options={
                'db_table': 'job_costs',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='JobOrderAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='job_orders/%Y/%m/', verbose_name='File')),
                ('description', models.CharField(blank=True, help_text='Keterangan singkat file, misal: PO Customer, Kontrak, dll.', max_length=255, verbose_name='Description')),
                ('job_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_order_attachments', to='job.joborder', verbose_name='Job Order Attachment')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_order_user_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Order Attachment',
                'verbose_name_plural': 'Job Order Attachments',
                'ordering': ['-created_at'],
            },
        ),
    ]
