# Generated by Django 5.2.6 on 2025-12-31 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobcosttype',
            options={'ordering': ['sort_order', 'name']},
        ),
        migrations.RenameField(
            model_name='jobcosttype',
            old_name='group',
            new_name='cost_group',
        ),
        migrations.RemoveField(
            model_name='jobcosttype',
            name='accrued_account',
        ),
        migrations.RemoveField(
            model_name='jobcosttype',
            name='cogs_account',
        ),
        migrations.RemoveField(
            model_name='joborder',
            name='hold_reason',
        ),
        migrations.AddField(
            model_name='jobcosttype',
            name='requires_vendor',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='jobcosttype',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
