# Generated by Django 5.2.6 on 2026-01-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_alter_jobcosttype_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcost',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
    ]
