# Generated by Django 5.2.6 on 2026-01-02 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_accountingsettings_auto_post_customer_receipt_and_more'),
        ('job', '0004_alter_joborder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcosttype',
            name='cogs_account',
            field=models.ForeignKey(blank=True, help_text='COGS account (debit) untuk accrual saat Job Completed', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account'),
        ),
    ]
