# Generated by Django 5.2.6 on 2026-01-03 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_jobcosttype_cogs_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcost',
            name='job_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_costs', to='job.joborder'),
        ),
    ]
