# Generated by Django 5.2.6 on 2026-01-03 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0015_journal_accounting__source__0fd9fd_idx'),
        ('job', '0006_alter_jobcost_job_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='joborder',
            name='complete_journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.journal'),
        ),
        migrations.AlterField(
            model_name='jobcost',
            name='cost_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_cost_types', to='job.jobcosttype'),
        ),
    ]
