# Generated by Django 5.2.6 on 2026-01-07 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_coresetting_text_value'),
        ('job', '0007_joborder_complete_journal_alter_jobcost_cost_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcost',
            name='currency',
            field=models.ForeignKey(blank=True, help_text='Currency of price', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.currency'),
        ),
        migrations.AddField(
            model_name='jobcost',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Unit price (foreign or local)', max_digits=18),
        ),
        migrations.AddField(
            model_name='jobcost',
            name='qty',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Quantity', max_digits=12),
        ),
        migrations.AddField(
            model_name='jobcost',
            name='rate',
            field=models.DecimalField(decimal_places=6, default=1, help_text='Currency rate to Job currency (IDR)', max_digits=18),
        ),
    ]
