# Generated by Django 5.2.6 on 2026-01-12 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0017_accountingsettings_auto_create_job_costing_journal_and_more'),
        ('job', '0008_jobcost_currency_jobcost_price_jobcost_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcosttype',
            name='accrued_liability_account',
            field=models.ForeignKey(blank=True, help_text='Liability/AP account (credit) untuk accrual saat Job Completed', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='jobcosttype',
            name='default_service_type',
            field=models.CharField(blank=True, choices=[('TRUCK', 'Trucking'), ('SEA', 'Sea'), ('AIR', 'Air'), ('PACKING', 'Packing'), ('DOCUMENT', 'Documentation'), ('OTHER', 'Other')], default='OTHER', help_text='Default schema modal untuk booking line', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobcosttype',
            name='cost_group',
            field=models.CharField(blank=True, choices=[('TRANSPORT', 'Transport'), ('SEA', 'Sea'), ('AIR', 'Air'), ('PACKING', 'Packing'), ('DOCUMENT', 'Documentation'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
    ]
