# Generated by Django 5.2.6 on 2026-01-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_jobcosttype_accrued_liability_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobcosttype',
            name='default_service_type',
        ),
        migrations.AddField(
            model_name='jobcosttype',
            name='service_type',
            field=models.CharField(blank=True, choices=[('TRUCK', 'Trucking'), ('SEA', 'Sea'), ('AIR', 'Air'), ('PACKING', 'Packing'), ('DOCUMENT', 'Documentation'), ('OTHER', 'Other')], help_text='Default schema modal untuk booking line', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobcosttype',
            name='cost_group',
            field=models.CharField(blank=True, choices=[('TRANSPORT', 'Transport'), ('PORT', 'Port & Terminal'), ('PACKING', 'Packing'), ('DOCUMENT', 'Documentation'), ('WAREHOUSE', 'Warehouse'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
    ]
