# Generated by Django 5.2.6 on 2026-01-15 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_remove_jobcosttype_default_service_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcosttype',
            name='cost_group',
            field=models.CharField(blank=True, choices=[('INLAND', 'Inland Freight'), ('SEA', 'Sea Freight'), ('AIR', 'Air Freight'), ('PORT', 'Port & Terminal'), ('WAREHOUSE', 'Warehouse'), ('DOCUMENT', 'Documentation'), ('PACKING', 'Packing'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
        migrations.AlterField(
            model_name='jobcosttype',
            name='service_type',
            field=models.CharField(blank=True, choices=[('INLAND', 'Inland Freight'), ('SEA', 'Sea Freight'), ('AIR', 'Air Freight'), ('PORT', 'Port & Terminal'), ('WAREHOUSE', 'Warehouse'), ('DOCUMENT', 'Documentation'), ('PACKING', 'Packing'), ('OTHER', 'Other')], help_text='Default schema modal untuk booking line', max_length=20),
        ),
    ]
