# Generated by Django 5.2.6 on 2026-01-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_alter_jobcosttype_cost_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcosttype',
            name='cost_group',
            field=models.CharField(blank=True, choices=[('INLAND', 'Inland Transportation'), ('SEA', 'Sea Freight'), ('AIR', 'Air Freight'), ('PORT', 'Customs Clearance'), ('PACKING', 'Packing / Lashing'), ('DOCUMENT', 'Documentation'), ('WAREHOUSE', 'Warehouse'), ('OTHER', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='jobcosttype',
            name='service_type',
            field=models.CharField(blank=True, help_text='Default schema modal untuk booking line', max_length=20),
        ),
    ]
