# Generated by Django 5.2.6 on 2026-01-16 23:38

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_alter_jobcosttype_cost_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobcost',
            name='category',
        ),
        migrations.AddField(
            model_name='jobcost',
            name='vb_allocated_qty',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total qty already allocated to Vendor Booking', max_digits=12),
        ),
        migrations.AddField(
            model_name='jobcost',
            name='vb_status',
            field=models.CharField(choices=[('NONE', 'Not Booked'), ('PARTIAL', 'Partially Booked'), ('FULL', 'Fully Booked')], db_index=True, default='NONE', help_text='Vendor Booking allocation status', max_length=10),
        ),
        migrations.AlterField(
            model_name='jobcost',
            name='actual_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Actual amount (after vendor invoice)', max_digits=18),
        ),
        migrations.AlterField(
            model_name='jobcost',
            name='est_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Estimated amount (system or manual)', max_digits=18),
        ),
        migrations.AlterField(
            model_name='jobcost',
            name='qty',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Quantity', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='jobcosttype',
            name='cost_group',
            field=models.CharField(blank=True, choices=[('INLAND', 'Inland'), ('SEA', 'Sea Freight'), ('AIR', 'Air Freight'), ('PORT', 'Customs Clearance'), ('PACKING', 'Packing / Lashing'), ('DOCUMENT', 'Documentation'), ('WAREHOUSE', 'Warehouse'), ('OTHER', 'Other')], max_length=50),
        ),
    ]
