# Generated by Django 5.2.6 on 2026-01-18 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_coresetting_text_value'),
        ('job', '0013_remove_jobcost_category_jobcost_vb_allocated_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcost',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Estimated amount (system or manual)', max_digits=18),
        ),
        migrations.AddField(
            model_name='jobcost',
            name='uom',
            field=models.CharField(blank=True, default='', help_text='Default UOM untuk cost line (mis: CNTR, CBM, KG, SHIPMENT, TRIP, DOC)', max_length=20),
        ),
        migrations.AddField(
            model_name='jobcosttype',
            name='taxes',
            field=models.ManyToManyField(blank=True, related_name='cost_lines_taxes', to='core.tax'),
        ),
        migrations.AddField(
            model_name='jobcosttype',
            name='uom',
            field=models.ForeignKey(blank=True, help_text='Default UOM untuk cost line (mis: LS, TRIP, CNTR, CBM, KG)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cost_line_uoms', to='core.uom'),
        ),
    ]
