# Generated by Django 5.2.6 on 2026-01-22 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0015_alter_jobcost_uom'),
        ('job', '0016_repair_job_costs_uom_id'),
    ]

    operations = [
    ]
