# Generated by Django 5.2.6 on 2026-01-23 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_coresetting_text_value'),
        ('job', '0017_merge_20260122_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcost',
            name='uom',
            field=models.ForeignKey(blank=True, help_text='Default UOM untuk cost line (mis: LS, TRIP, CNTR, CBM, KG)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job_cost_uoms', to='core.uom'),
        ),
    ]
