# Generated by Django 5.2.6 on 2026-01-23 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0018_alter_jobcost_uom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobcosttype',
            name='uom',
        ),
    ]
