# Generated by Django 5.2.6 on 2026-01-23 12:25

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0019_remove_jobcosttype_uom'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobFeePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='Pakai tanggal 1 setiap bulan (YYYY-MM-01).', unique=True)),
                ('percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('PAID', 'Paid')], default='DRAFT', max_length=16)),
                ('total_base_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('total_fee_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_fee_periods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-month',),
            },
        ),
        migrations.CreateModel(
            name='JobFeeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fee_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sales_fee_line', to='job.joborder')),
                ('sales_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_fee_lines', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='job.jobfeeperiod')),
            ],
            options={
                'ordering': ('sales_user', 'job_order'),
            },
        ),
    ]
