# Generated by Django 5.2.6 on 2026-01-23 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_coresetting_text_value'),
        ('job', '0020_jobfeeperiod_jobfeeline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobcost',
            name='uom',
        ),
        migrations.AddField(
            model_name='jobcosttype',
            name='uom',
            field=models.ForeignKey(blank=True, help_text='Default UOM untuk cost line (mis: LS, TRIP, CNTR, CBM, KG)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cost_line_uoms', to='core.uom'),
        ),
    ]
