# Generated by Django 5.2.6 on 2026-01-24 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0007_location_altitude_location_country_code_and_more'),
        ('job', '0022_add_jobcosttype_uom_id_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='joborder',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job_orders_destination', to='geo.location'),
        ),
        migrations.AddField(
            model_name='joborder',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job_orders_origin', to='geo.location'),
        ),
    ]
