# Generated by Django 5.2.6 on 2026-01-25 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_coresetting_text_value'),
        ('job', '0023_joborder_destination_joborder_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='joborder',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='joborder',
            name='qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='joborder',
            name='taxes',
            field=models.ManyToManyField(blank=True, related_name='job_taxes', to='core.tax'),
        ),
    ]
