# Generated by Django 5.2.6 on 2026-01-25 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0024_joborder_price_joborder_qty_joborder_taxes'),
    ]

    operations = [
        migrations.AddField(
            model_name='joborder',
            name='consignee_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='joborder',
            name='shipper_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
