# Generated by Django 5.2.6 on 2026-01-25 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0025_joborder_consignee_name_joborder_shipper_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joborder',
            name='consignee_name',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='joborder',
            name='shipper_name',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
