# Generated by Django 5.2.6 on 2026-01-25 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0026_alter_joborder_consignee_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joborder',
            name='cargo_description',
            field=models.TextField(blank=True, help_text='Deskripsi singkat cargo.'),
        ),
        migrations.AlterField(
            model_name='joborder',
            name='consignee_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='joborder',
            name='delivery',
            field=models.TextField(blank=True, help_text='Alamat / lokasi pengantaran.', verbose_name='Delivery'),
        ),
        migrations.AlterField(
            model_name='joborder',
            name='pickup',
            field=models.TextField(blank=True, help_text='Alamat / lokasi penjemputan.', verbose_name='Pick Up'),
        ),
        migrations.AlterField(
            model_name='joborder',
            name='shipper_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
