# Generated by Django 5.2.6 on 2026-01-25 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0027_alter_joborder_cargo_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joborder',
            name='cargo_dimension',
            field=models.TextField(blank=True, help_text='Goods or matrial package and dimensions'),
        ),
        migrations.AlterField(
            model_name='joborder',
            name='cargo_description',
            field=models.TextField(blank=True, help_text='Goods or matrials description.'),
        ),
    ]
