# Generated by Django 5.2.6 on 2026-01-25 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0029_joborderattachment_customer_note_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joborderattachment',
            name='customer_note',
        ),
        migrations.RemoveField(
            model_name='joborderattachment',
            name='sla_note',
        ),
        migrations.AddField(
            model_name='joborder',
            name='customer_note',
            field=models.CharField(blank=True, help_text='Type your attension for your customer', max_length=255, verbose_name='Customer Notes'),
        ),
        migrations.AddField(
            model_name='joborder',
            name='sla_note',
            field=models.CharField(blank=True, help_text='Types your service level agreements.', max_length=255, verbose_name='Description'),
        ),
    ]
