# Generated by Django 5.2.6 on 2026-01-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0030_remove_joborderattachment_customer_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joborder',
            name='customer_note',
            field=models.TextField(blank=True, help_text='Type your attension for your customer', max_length=255, verbose_name='Customer Notes'),
        ),
        migrations.AlterField(
            model_name='joborder',
            name='sla_note',
            field=models.TextField(blank=True, help_text='Types your service level agreements.', max_length=255, verbose_name='Description'),
        ),
    ]
