# Generated by Django 5.2.6 on 2026-01-25 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0031_alter_joborder_customer_note_alter_joborder_sla_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joborder',
            name='customer_note',
            field=models.TextField(blank=True, help_text='Type your attension for your customer', verbose_name='Customer Notes'),
        ),
        migrations.AlterField(
            model_name='joborder',
            name='sla_note',
            field=models.TextField(blank=True, help_text='Types your service level agreements.', verbose_name='Description'),
        ),
    ]
