# Generated by Django 5.2.6 on 2026-01-29 09:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0032_alter_joborder_customer_note_alter_joborder_sla_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='Quotation No')),
                ('quote_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Quote Date')),
                ('valid_until', models.DateField(blank=True, db_index=True, null=True, verbose_name='Valid Until')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('ORDERED', 'Ordered')], db_index=True, default='DRAFT', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('job_order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='quotation', to='job.joborder')),
            ],
            options={
                'db_table': 'quotations',
                'ordering': ['-quote_date', '-id'],
                'indexes': [models.Index(fields=['status', 'valid_until'], name='quotations_status_fa1d63_idx')],
            },
        ),
    ]
