# Generated by Django 5.2.6 on 2026-02-03 11:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0032_alter_joborder_customer_note_alter_joborder_sla_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='joborder',
            name='status',
            field=models.CharField(choices=[('QUOTATION', 'Quotation'), ('DRAFT', 'Draft'), ('IN_PROGRESS', 'In Progress'), ('ON_HOLD', 'On Hold'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], db_index=True, default='DRAFT', max_length=20),
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('EXPIRED', 'Expired'), ('ORDERED', 'Ordered'), ('CANCELED', 'Canceled')], db_index=True, default='DRAFT', max_length=20)),
                ('number', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='Quotation No')),
                ('quote_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Quote Date')),
                ('valid_until', models.DateField(blank=True, db_index=True, null=True, verbose_name='Valid Until')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('expired_by_system', models.BooleanField(default=False)),
                ('ordered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotation', to='job.joborder')),
                ('ordered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_quotations', to=settings.AUTH_USER_MODEL)),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_quotations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quotations',
                'ordering': ['-quote_date', '-id'],
                'permissions': [('can_send_quotation', 'Can send quotation'), ('can_convert_quotation', 'Can convert quotation to order')],
                'indexes': [models.Index(fields=['status', 'valid_until'], name='quotations_status_fa1d63_idx')],
            },
        ),
    ]
