# Generated by Django 5.2.6 on 2026-02-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0033_alter_joborder_status_quotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='joborder',
            name='shp_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
    ]
