# Generated by Django 5.2.6 on 2026-01-29 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0033_quotation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='rejected_at',
        ),
        migrations.AlterField(
            model_name='joborder',
            name='status',
            field=models.CharField(choices=[('QUOTATION', 'Quotation'), ('DRAFT', 'Draft'), ('IN_PROGRESS', 'In Progress'), ('ON_HOLD', 'On Hold'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], db_index=True, default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='job_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotation', to='job.joborder'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('EXPIRED', 'Expired'), ('ORDERED', 'Ordered')], db_index=True, default='DRAFT', max_length=20),
        ),
    ]
