# Generated by Django 5.2.6 on 2026-02-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0035_quotation_cancel_reason_quotation_canceled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joborder',
            name='term_conditions',
            field=models.TextField(blank=True),
        ),
    ]
