# Generated by Django 5.2.6 on 2026-02-10 21:30

import django_summernote.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0036_joborder_term_conditions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joborder',
            name='customer_note',
            field=django_summernote.fields.SummernoteTextField(blank=True, help_text='Type your attension for your customer', verbose_name='Customer Notes'),
        ),
        migrations.AlterField(
            model_name='joborder',
            name='term_conditions',
            field=django_summernote.fields.SummernoteTextField(blank=True),
        ),
    ]
