# Generated by Django 5.2.6 on 2026-02-19 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0037_alter_joborder_customer_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joborder',
            name='discount_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='joborder',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('PERCENT', 'Percent'), ('AMOUNT', 'Amount')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='joborder',
            name='discount_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='joborder',
            name='hold_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='joborder',
            name='status',
            field=models.CharField(choices=[('QUOTATION', 'Quotation'), ('DRAFT', 'Draft'), ('IN_COSTING', 'In Costing'), ('IN_PROGRESS', 'In Progress'), ('ON_HOLD', 'On Hold'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], db_index=True, default='DRAFT', max_length=20),
        ),
    ]
