# Generated by Django 5.2.6 on 2026-02-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0038_joborder_discount_notes_joborder_discount_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joborder',
            name='discount_type',
            field=models.CharField(choices=[('PERCENT', 'Percent'), ('AMOUNT', 'Fixed Amount')], default='PERCENT', max_length=10),
        ),
    ]
