# Generated by Django 5.2.6 on 2026-02-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0039_alter_joborder_discount_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='joborder',
            name='down_payment_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='joborder',
            name='is_proforma',
            field=models.BooleanField(default=False),
        ),
    ]
