# Generated by Django 5.2.6 on 2026-02-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0040_joborder_down_payment_percent_joborder_is_proforma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joborder',
            name='pph_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
    ]
