# Generated by Django 5.2.6 on 2026-02-22 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0041_alter_joborder_pph_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='joborder',
            name='job_source',
            field=models.CharField(blank=True, choices=[('QUOTATION', 'Quotation'), ('CUSTOMER_PO', 'Customer PO'), ('EMAIL', 'Email')], max_length=20, null=True),
        ),
    ]
