# Generated by Django 5.2.6 on 2026-02-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0042_joborder_job_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='joborder',
            name='bank_transfer_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
