# Generated by Django 5.2.6 on 2026-02-22 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0043_joborder_bank_transfer_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joborder',
            name='job_source',
            field=models.CharField(blank=True, choices=[('CUSTOMER_PO', 'Customer PO'), ('EMAIL', 'Email')], max_length=20, null=True),
        ),
    ]
