# Generated by Django 5.2.6 on 2025-10-15 05:08

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
        ('partners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('symbol', models.CharField(blank=True, max_length=8, null=True)),
                ('decimals', models.PositiveSmallIntegerField(default=2)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'currencies',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('days', models.PositiveSmallIntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'payment_terms',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SalesService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sales_services',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'uoms',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SalesNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_type', models.CharField(default='freight', max_length=20)),
                ('period', models.CharField(max_length=6)),
                ('prefix', models.CharField(default='FQ', max_length=30)),
                ('padding', models.PositiveSmallIntegerField(default=5)),
                ('last_no', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sales_number_sequences',
                'ordering': ['-period'],
                'unique_together': {('business_type', 'period')},
            },
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('vat', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed'), ('ON_PROGRESS', 'On Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('ON_HOLD', 'On Hold')], default='DRAFT', max_length=20)),
                ('business_type', models.CharField(default='freight', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='sales.currency')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='partners.partner')),
                ('payment_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='sales.paymentterm')),
                ('sales_agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agency_orders', to='partners.partner')),
                ('sales_user', models.ForeignKey(blank=True, db_column='sales_user_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sales_orders',
            },
        ),
        migrations.CreateModel(
            name='SalesModule',
            fields=[
            ],
            options={
                'verbose_name': 'Sales module',
                'verbose_name_plural': 'Sales module',
                'permissions': (('access_sales', 'Can access Sales module'), ('view_all_sales', 'Can view all sales data')),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sales.salesorder',),
        ),
        migrations.CreateModel(
            name='SalesQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('ACCEPTED', 'Accepted'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('ORDERED', 'Ordered')], default='DRAFT', max_length=20)),
                ('number', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('vat', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('note_1', models.TextField(blank=True, null=True)),
                ('note_2', models.TextField(blank=True, null=True)),
                ('amount_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('business_type', models.CharField(default='freight', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='sales.currency')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='partners.partner')),
                ('payment_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='sales.paymentterm')),
                ('sales_agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agency_quotations', to='partners.partner')),
                ('sales_user', models.ForeignKey(blank=True, db_column='sales_user_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_quotations', to=settings.AUTH_USER_MODEL)),
                ('sales_service', models.ForeignKey(db_column='sales_service_id', on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='sales.salesservice', to_field='code')),
            ],
            options={
                'db_table': 'sales_quotations',
            },
        ),
        migrations.AddField(
            model_name='salesorder',
            name='sales_quotation',
            field=models.ForeignKey(blank=True, db_column='sales_quotation_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='sales.salesquotation'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='sales_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='sales.salesservice'),
        ),
        migrations.CreateModel(
            name='SalesQuotationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('qty', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotation_destination_lines', to='geo.location')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotation_origin_lines', to='geo.location')),
                ('sales_quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.salesquotation')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.uom')),
            ],
            options={
                'db_table': 'sales_quotation_lines',
            },
        ),
        migrations.CreateModel(
            name='SalesOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('qty', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_destination_lines', to='geo.location')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_origin_lines', to='geo.location')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.salesorder')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.uom')),
            ],
            options={
                'db_table': 'sales_order_lines',
            },
        ),
    ]
