# Generated by Django 5.2.6 on 2025-10-22 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_last_no_numbersequence_last_number'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesquotation',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='core.currency'),
        ),
        migrations.AlterField(
            model_name='salesquotation',
            name='payment_term',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='core.paymentterm'),
        ),
        migrations.AlterField(
            model_name='salesquotation',
            name='valid_until',
            field=models.DateField(null=True),
        ),
    ]
