# Generated by Django 5.2.6 on 2025-10-22 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_last_no_numbersequence_last_number'),
        ('sales', '0002_alter_salesquotation_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesquotation',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='core.currency'),
        ),
    ]
