# Generated by Django 5.2.6 on 2025-09-21 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_salesquotation_total_amount_alter_salesorder_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='sales_quotation',
            field=models.ForeignKey(blank=True, db_column='sales_quotation_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='sales.salesquotation'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='quotation',
            field=models.ForeignKey(blank=True, db_column='quotation_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sales.salesquotation'),
        ),
    ]
