# Generated by Django 5.2.6 on 2025-10-24 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_companyprofile'),
        ('sales', '0003_alter_salesquotation_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesquotation',
            name='sales_service',
            field=models.ForeignKey(db_column='sales_service_id', on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='core.salesservice'),
        ),
    ]
