# Generated by Django 5.2.6 on 2025-11-11 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_value_amount_project_value_currency_code_and_more'),
        ('sales', '0004_alter_salesquotation_sales_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_order', to='projects.project'),
        ),
    ]
