# Generated by Django 5.2.6 on 2025-09-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_salesquotation_grand_total_salesquotation_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesquotation',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('ACCEPTED', 'Accepted'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('ORDERED', 'Ordered')], default='DRAFT', max_length=20),
        ),
    ]
