# Generated by Django 5.2.6 on 2025-11-18 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_core_number_app_lab_f5e3ec_idx_core_number_app_lab_9c97e4_idx_and_more'),
        ('geo', '0007_location_altitude_location_country_code_and_more'),
        ('partners', '0007_partner_company'),
        ('sales', '0005_salesorder_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FreightQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(db_index=True, max_length=30, unique=True)),
                ('quotation_date', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent to customer'), ('ACCEPTED', 'Accepted'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('ORDERED', 'Converted to Order')], db_index=True, default='DRAFT', max_length=20)),
                ('cargo_name', models.CharField(blank=True, max_length=200)),
                ('hs_code', models.CharField(blank=True, max_length=30)),
                ('commodity', models.CharField(blank=True, max_length=200)),
                ('package_count', models.PositiveIntegerField(blank=True, null=True)),
                ('package_type', models.CharField(blank=True, max_length=50)),
                ('gross_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('weight_uom', models.CharField(blank=True, default='KGS', max_length=10)),
                ('volume_cbm', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('volume_uom', models.CharField(blank=True, default='CBM', max_length=10)),
                ('is_dg', models.BooleanField(default=False)),
                ('dg_class', models.CharField(blank=True, max_length=50)),
                ('ready_date', models.DateField(blank=True, null=True)),
                ('shipper_name', models.CharField(blank=True, max_length=255)),
                ('shipper_address', models.TextField(blank=True)),
                ('consignee_name', models.CharField(blank=True, max_length=255)),
                ('consignee_address', models.TextField(blank=True)),
                ('notes_internal', models.TextField(blank=True)),
                ('notes_customer', models.TextField(blank=True)),
                ('consignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='freight_quotations_as_consignee', to='partners.partner')),
                ('customer', models.ForeignKey(limit_choices_to={'is_individual': False}, on_delete=django.db.models.deletion.PROTECT, related_name='freight_quotations', to='partners.partner')),
                ('customer_contact', models.ForeignKey(blank=True, limit_choices_to={'is_individual': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='freight_quotations_contact', to='partners.partner')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='freight_qtn_destination_set', to='geo.location')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='freight_qtn_origin_set', to='geo.location')),
                ('sales_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='freight_quotations', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(help_text='Mis: Sea Door to Door, Sea Port to Port, dll.', on_delete=django.db.models.deletion.PROTECT, related_name='freight_quotations', to='core.salesservice')),
                ('shipper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='freight_quotations_as_shipper', to='partners.partner')),
            ],
            options={
                'db_table': 'sales_freight_quotations',
                'ordering': ['-quotation_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FreightOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(db_index=True, max_length=30, unique=True)),
                ('order_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], db_index=True, default='DRAFT', max_length=20)),
                ('shipper_name', models.CharField(blank=True, max_length=255)),
                ('shipper_address', models.TextField(blank=True)),
                ('consignee_name', models.CharField(blank=True, max_length=255)),
                ('consignee_address', models.TextField(blank=True)),
                ('cargo_name', models.CharField(blank=True, max_length=200)),
                ('package_count', models.PositiveIntegerField(blank=True, null=True)),
                ('package_type', models.CharField(blank=True, max_length=50)),
                ('gross_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('volume_cbm', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('notes_internal', models.TextField(blank=True)),
                ('customer', models.ForeignKey(limit_choices_to={'is_individual': False}, on_delete=django.db.models.deletion.PROTECT, related_name='freight_orders', to='partners.partner')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='freight_orders_destination_set', to='geo.location')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='freight_orders_origin_set', to='geo.location')),
                ('sales_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='freight_orders', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='freight_orders', to='core.salesservice')),
                ('quotation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='freight_order', to='sales.freightquotation')),
            ],
            options={
                'db_table': 'sales_freight_orders',
                'ordering': ['-order_date', '-id'],
            },
        ),
    ]
