# Generated by Django 5.2.6 on 2025-09-22 00:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_salesquotation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorderline',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='salesorderline',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
