# Generated by Django 5.2.6 on 2025-11-19 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0007_location_altitude_location_country_code_and_more'),
        ('partners', '0007_partner_company'),
        ('sales', '0007_freightquotation_amount_freightquotation_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freightquotation',
            name='shipper_name',
        ),
        migrations.AddField(
            model_name='freightquotation',
            name='shipper_contact_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='freightquotation',
            name='shipper_district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fq_shipper_district', to='geo.location'),
        ),
        migrations.AddField(
            model_name='freightquotation',
            name='shipper_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='freightquotation',
            name='shipper_province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fq_shipper_province', to='geo.location'),
        ),
        migrations.AddField(
            model_name='freightquotation',
            name='shipper_regency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fq_shipper_regency', to='geo.location'),
        ),
        migrations.AddField(
            model_name='freightquotation',
            name='shipper_village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fq_shipper_village', to='geo.location'),
        ),
        migrations.AlterField(
            model_name='freightquotation',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='freight_quotations_as_customer', to='partners.partner'),
        ),
    ]
