# Generated by Django 5.2.6 on 2025-09-23 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_remove_salesorderline_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesorder',
            options={'permissions': (('access_sales', 'Can access Sales module'),)},
        ),
    ]
