# Generated by Django 5.2.6 on 2025-09-23 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_alter_salesorder_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesModule',
            fields=[
            ],
            options={
                'verbose_name': 'Sales module',
                'verbose_name_plural': 'Sales module',
                'permissions': (('access_sales', 'Can access Sales module'),),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sales.salesorder',),
        ),
        migrations.AlterModelOptions(
            name='salesorder',
            options={},
        ),
    ]
