# Generated by Django 5.2.6 on 2025-11-19 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_core_number_app_lab_f5e3ec_idx_core_number_app_lab_9c97e4_idx_and_more'),
        ('geo', '0007_location_altitude_location_country_code_and_more'),
        ('partners', '0007_partner_company'),
        ('sales', '0008_remove_freightquotation_shipper_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freightquotation',
            name='consignee_district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fq_consignee_district', to='geo.location'),
        ),
        migrations.AddField(
            model_name='freightquotation',
            name='consignee_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='freightquotation',
            name='consignee_province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fq_consignee_province', to='geo.location'),
        ),
        migrations.AddField(
            model_name='freightquotation',
            name='consignee_regency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fq_consignee_regency', to='geo.location'),
        ),
        migrations.AddField(
            model_name='freightquotation',
            name='consignee_village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fq_consignee_village', to='geo.location'),
        ),
        migrations.AlterField(
            model_name='freightorder',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='freight_orders', to='partners.partner'),
        ),
        migrations.AlterField(
            model_name='freightquotation',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.currency'),
        ),
        migrations.AlterField(
            model_name='freightquotation',
            name='customer_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='freight_quotations_customer_contact', to='partners.partner'),
        ),
        migrations.AlterField(
            model_name='freightquotation',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='freight_quotations_destination', to='geo.location'),
        ),
        migrations.AlterField(
            model_name='freightquotation',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='freight_quotations_origin', to='geo.location'),
        ),
        migrations.AlterField(
            model_name='freightquotation',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='freight_quotations_service', to='core.salesservice'),
        ),
    ]
