# Generated by Django 5.2.6 on 2025-11-20 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_core_number_app_lab_f5e3ec_idx_core_number_app_lab_9c97e4_idx_and_more'),
        ('sales', '0009_freightquotation_consignee_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freightorder',
            name='payment_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='freight_quotations', to='core.paymentterm'),
        ),
    ]
