# Generated by Django 5.2.6 on 2025-11-20 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_core_number_app_lab_f5e3ec_idx_core_number_app_lab_9c97e4_idx_and_more'),
        ('sales', '0010_freightorder_payment_term'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freightorder',
            old_name='sales_person',
            new_name='sales_user',
        ),
        migrations.RenameField(
            model_name='freightquotation',
            old_name='sales_person',
            new_name='sales_user',
        ),
        migrations.RemoveField(
            model_name='freightorder',
            name='service',
        ),
        migrations.RemoveField(
            model_name='freightquotation',
            name='service',
        ),
        migrations.AddField(
            model_name='freightorder',
            name='sales_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='freight_orders', to='core.salesservice'),
        ),
        migrations.AddField(
            model_name='freightquotation',
            name='sales_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='freight_quotations_service', to='core.salesservice'),
        ),
    ]
