# Generated by Django 5.2.6 on 2025-09-23 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_salesorder_salesperson_salesquotation_salesperson'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesmodule',
            options={'permissions': (('access_sales', 'Can access Sales module'), ('view_all_sales', 'Can view all sales data')), 'verbose_name': 'Sales module', 'verbose_name_plural': 'Sales module'},
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='sales_user_id',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='salesperson',
        ),
        migrations.RemoveField(
            model_name='salesquotation',
            name='sales_user_id',
        ),
        migrations.RemoveField(
            model_name='salesquotation',
            name='salesperson',
        ),
        migrations.AddField(
            model_name='salesorder',
            name='sales_user',
            field=models.ForeignKey(blank=True, db_column='sales_user_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesquotation',
            name='sales_user',
            field=models.ForeignKey(blank=True, db_column='sales_user_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_quotations', to=settings.AUTH_USER_MODEL),
        ),
    ]
