# Generated by Django 5.2.6 on 2025-11-21 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0007_partner_company'),
        ('sales', '0012_freightquotation_payment_term_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freightquotation',
            name='sales_agent',
            field=models.ForeignKey(blank=True, db_column='sales_agent_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='freight_quotations_as_agent', to='partners.partner'),
        ),
    ]
