# Generated by Django 5.2.6 on 2025-11-21 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0007_partner_company'),
        ('sales', '0013_freightquotation_sales_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freightquotation',
            name='sales_agent',
        ),
        migrations.AddField(
            model_name='freightorder',
            name='sales_agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_agency_order', to='partners.partner'),
        ),
        migrations.AddField(
            model_name='freightquotation',
            name='sales_agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_agency_quotations', to='partners.partner'),
        ),
    ]
