# Generated by Django 5.2.6 on 2025-11-21 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_core_number_app_lab_f5e3ec_idx_core_number_app_lab_9c97e4_idx_and_more'),
        ('sales', '0014_remove_freightquotation_sales_agent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freightquotation',
            name='package_uom_fk',
            field=models.ForeignKey(blank=True, limit_choices_to={'category__iexact': 'count'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fq_package', to='core.uom'),
        ),
        migrations.AddField(
            model_name='freightquotation',
            name='volume_uom_fk',
            field=models.ForeignKey(blank=True, limit_choices_to={'category__iexact': 'volume'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fq_volume', to='core.uom'),
        ),
        migrations.AddField(
            model_name='freightquotation',
            name='weight_uom_fk',
            field=models.ForeignKey(blank=True, limit_choices_to={'category__iexact': 'weight'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fq_weight', to='core.uom'),
        ),
    ]
