# Generated by Django 5.2.6 on 2025-11-21 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_core_number_app_lab_f5e3ec_idx_core_number_app_lab_9c97e4_idx_and_more'),
        ('sales', '0015_freightquotation_package_uom_fk_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freightquotation',
            old_name='dg_class',
            new_name='dangerous_goods_class',
        ),
        migrations.RenameField(
            model_name='freightquotation',
            old_name='is_dg',
            new_name='is_dangerous_goods',
        ),
        migrations.RenameField(
            model_name='freightquotation',
            old_name='package_uom_fk',
            new_name='package_uom',
        ),
        migrations.RenameField(
            model_name='freightquotation',
            old_name='ready_date',
            new_name='shipmen_plan_date',
        ),
        migrations.RemoveField(
            model_name='freightquotation',
            name='volume_cbm',
        ),
        migrations.RemoveField(
            model_name='freightquotation',
            name='volume_uom_fk',
        ),
        migrations.RemoveField(
            model_name='freightquotation',
            name='weight_uom_fk',
        ),
        migrations.AlterField(
            model_name='freightquotation',
            name='volume_uom',
            field=models.ForeignKey(blank=True, limit_choices_to={'category__iexact': 'volume'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fq_volume', to='core.uom'),
        ),
        migrations.AlterField(
            model_name='freightquotation',
            name='weight_uom',
            field=models.ForeignKey(blank=True, limit_choices_to={'category__iexact': 'weight'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fq_weight', to='core.uom'),
        ),
    ]
