# Generated by Django 5.2.6 on 2025-11-21 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_core_number_app_lab_f5e3ec_idx_core_number_app_lab_9c97e4_idx_and_more'),
        ('sales', '0016_rename_dg_class_freightquotation_dangerous_goods_class_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freightquotation',
            old_name='shipmen_plan_date',
            new_name='shipment_plan_date',
        ),
        migrations.AddField(
            model_name='freightorder',
            name='dangerous_goods_class',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='freightorder',
            name='is_dangerous_goods',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='freightorder',
            name='package_uom',
            field=models.ForeignKey(blank=True, limit_choices_to={'category__iexact': 'count'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fo_package', to='core.uom'),
        ),
        migrations.AddField(
            model_name='freightorder',
            name='shipment_plan_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='freightorder',
            name='volume_uom',
            field=models.ForeignKey(blank=True, limit_choices_to={'category__iexact': 'volume'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fo_volume', to='core.uom'),
        ),
        migrations.AddField(
            model_name='freightorder',
            name='weight_uom',
            field=models.ForeignKey(blank=True, limit_choices_to={'category__iexact': 'weight'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fq_weight', to='core.uom'),
        ),
        migrations.AddField(
            model_name='freightquotation',
            name='volume_cbm',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='freightquotation',
            name='weight_uom',
            field=models.ForeignKey(blank=True, limit_choices_to={'category__iexact': 'weight'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fo_weight', to='core.uom'),
        ),
    ]
