# Generated by Django 5.2.6 on 2025-11-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_freightorder_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freightorder',
            name='ref_number',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='freightorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('ON_PROGRESS', 'On Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('HOLDED', 'Holded')], db_index=True, default='DRAFT', max_length=20),
        ),
    ]
