# Generated by Django 5.2.6 on 2025-11-29 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0020_freightorder_ref_number_alter_freightorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='freightorder',
            name='notes_customer',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='freightorder',
            name='reference_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='freightorder',
            name='reference_type',
            field=models.CharField(blank=True, choices=[('CUSTOMER_PO', 'Customer PO'), ('EMAIL', 'Email'), ('QUOTATION', 'Quotation')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='freightquotation',
            name='reference_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='freightquotation',
            name='reference_type',
            field=models.CharField(blank=True, choices=[('CUSTOMER_PO', 'Customer PO'), ('EMAIL', 'Email'), ('QUOTATION', 'Quotation')], max_length=30, null=True),
        ),
    ]
