# Generated by Django 5.2.6 on 2025-11-29 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0021_freightorder_notes_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freightorder',
            name='down_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
