# Generated by Django 5.2.6 on 2025-11-30 01:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0022_freightorder_down_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='freightorder',
            name='reference_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='freightorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('HOLDED', 'Holded')], db_index=True, default='DRAFT', max_length=20),
        ),
    ]
