# Generated by Django 5.2.6 on 2025-12-01 11:31

import django.db.models.deletion
from django.db import migrations, models

def set_default_currency(apps, schema_editor):
    FreightOrder = apps.get_model("sales", "FreightOrder")
    Currency = apps.get_model("core", "Currency")

    try:
        idr = Currency.objects.get(code="IDR")
    except Currency.DoesNotExist:
        return  # kalau belum ada currency IDR, skip

    FreightOrder.objects.filter(currency__isnull=True).update(currency=idr)




class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_core_number_app_lab_f5e3ec_idx_core_number_app_lab_9c97e4_idx_and_more'),
        ('sales', '0023_freightorder_reference_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freightorder',
            name='currency',
            field=models.ForeignKey(
                to='core.currency',
                null=False,
                blank=False,
                on_delete=models.PROTECT,
                related_name='freight_orders',
            ),
        ),
        migrations.RunPython(set_default_currency),
    ]
