# Generated by Django 5.2.6 on 2025-12-01 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_core_number_app_lab_f5e3ec_idx_core_number_app_lab_9c97e4_idx_and_more'),
        ('sales', '0024_freightorder_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freightorder',
            name='currency',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='freight_orders', to='core.currency'),
        ),
    ]
