# Generated by Django 5.2.6 on 2025-12-01 21:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_core_number_app_lab_f5e3ec_idx_core_number_app_lab_9c97e4_idx_and_more'),
        ('partners', '0007_partner_company'),
        ('sales', '0025_alter_freightorder_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FreightInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, help_text='Nomor invoice (auto generate dari NumberSequence)', max_length=30, unique=True)),
                ('invoice_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField()),
                ('subtotal_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total yang ditagihkan ke customer.', max_digits=18)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, help_text='Total pembayaran yang sudah diterima.', max_digits=18)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent to customer'), ('PARTIAL', 'Partially Paid'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('notes_internal', models.TextField(blank=True, help_text='Catatan internal, tidak tampil di invoice customer.')),
                ('notes_customer', models.TextField(blank=True, help_text='Catatan yang akan tampil di invoice (footer / remarks).')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='freight_invoices_created', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='freight_invoices', to='core.currency')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='freight_invoices', to='partners.partner')),
                ('freight_order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='sales.freightorder')),
                ('payment_term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='freight_invoices', to='core.paymentterm')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='freight_invoices_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Freight Invoice',
                'verbose_name_plural': 'Freight Invoices',
                'ordering': ['-invoice_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FreightInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=18)),
                ('uom', models.CharField(blank=True, max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.freightinvoice')),
            ],
            options={
                'ordering': ['invoice', 'sort_order', 'id'],
            },
        ),
    ]
