# Generated by Django 5.2.6 on 2025-12-01 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0026_freightinvoice_freightinvoiceline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freightinvoice',
            name='freight_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='sales.freightorder'),
        ),
    ]
