# Generated by Django 5.2.6 on 2025-12-02 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0028_remove_freightinvoiceline_invoice_invoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='category',
            field=models.CharField(choices=[('FREIGHT', 'Freight'), ('AGENCY', 'Agency'), ('SHIP_CHARTER', 'Ship Charter')], default='FREIGHT', help_text='Kategori bisnis invoice ini (Freight, Agency, Ship Charter, dll).', max_length=20),
        ),
    ]
