# Generated by Django 5.2.6 on 2025-12-07 05:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_service'),
        ('partners', '0007_partner_company'),
        ('sales', '0029_invoice_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=30, unique=True, verbose_name='Job No')),
                ('job_date', models.DateField(verbose_name='Date')),
                ('cargo_description', models.CharField(blank=True, help_text='Deskripsi singkat cargo.', max_length=255)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, help_text='Jumlah / volume cargo (opsional).', max_digits=10, null=True)),
                ('pickup', models.CharField(blank=True, help_text='Alamat / lokasi penjemputan.', max_length=255, verbose_name='Pick Up')),
                ('delivery', models.CharField(blank=True, help_text='Alamat / lokasi pengantaran.', max_length=255, verbose_name='Delivery')),
                ('pic', models.CharField(blank=True, help_text='Nama PIC.', max_length=100, verbose_name='PIC')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pph_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('remarks_internal', models.TextField(blank=True, help_text='Catatan internal untuk tim.')),
                ('currency', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.currency')),
                ('customer', models.ForeignKey(help_text='Relasi ke partner dengan role customer.', on_delete=django.db.models.deletion.PROTECT, related_name='customer_job', to='partners.partner', verbose_name='Customer')),
                ('payment_term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_payments', to='core.paymentterm', verbose_name='Payment Term')),
                ('sales_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job_sales', to=settings.AUTH_USER_MODEL, verbose_name='Sales')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_services', to='core.salesservice', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'ordering': ['-job_date', '-id'],
            },
        ),
    ]
