# Generated by Django 5.2.6 on 2025-12-07 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_service'),
        ('sales', '0030_joborder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joborder',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_services', to='core.service', verbose_name='Service'),
        ),
    ]
