# Generated by Django 5.2.6 on 2025-12-08 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0031_alter_joborder_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='joborder',
            name='is_pph',
            field=models.BooleanField(default=False, verbose_name='Apply PPH'),
        ),
        migrations.AddField(
            model_name='joborder',
            name='is_tax',
            field=models.BooleanField(default=False, verbose_name='Apply Tax 1.1 (VAT)'),
        ),
    ]
