# Generated by Django 5.2.6 on 2025-12-08 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0008_customer'),
        ('sales', '0032_joborder_is_pph_joborder_is_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joborder',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_job', to='partners.customer', verbose_name='Customer'),
        ),
    ]
