# Generated by Django 5.2.6 on 2025-12-08 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0008_customer'),
        ('sales', '0033_alter_joborder_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joborder',
            name='customer',
            field=models.ForeignKey(limit_choices_to=models.Q(('roles__code', 'customer')), on_delete=django.db.models.deletion.PROTECT, related_name='customer_job', to='partners.partner', verbose_name='Customer'),
        ),
    ]
