# Generated by Django 5.2.6 on 2025-12-08 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0035_alter_joborder_customer'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='joborder',
            table='sales_job_orders',
        ),
    ]
