# Generated by Django 5.2.6 on 2025-12-08 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0036_alter_joborder_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('qty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='sales.joborder')),
            ],
            options={
                'db_table': 'sales_job_costs',
                'ordering': ['id'],
            },
        ),
    ]
