# Generated by Django 5.2.6 on 2025-12-09 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0037_jobcost'),
    ]

    operations = [
        migrations.AddField(
            model_name='joborder',
            name='order_number',
            field=models.CharField(blank=True, help_text='Customer ref eg. PO#', max_length=30, null=True),
        ),
    ]
