# Generated by Django 5.2.6 on 2025-12-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0038_joborder_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='joborder',
            name='curs_idr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='joborder',
            name='total_in_idr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='joborder',
            name='order_number',
            field=models.CharField(blank=True, help_text='Customer reference eg. PO#', max_length=30, null=True),
        ),
    ]
