# Generated by Django 5.2.6 on 2025-12-10 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0039_joborder_curs_idr_joborder_total_in_idr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joborder',
            name='curs_idr',
        ),
        migrations.AddField(
            model_name='joborder',
            name='kurs_idr',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
        ),
    ]
