# Generated by Django 5.2.6 on 2025-12-12 01:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0040_remove_joborder_curs_idr_joborder_kurs_idr'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOrderAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='job_orders/%Y/%m/', verbose_name='File')),
                ('description', models.CharField(blank=True, help_text='Keterangan singkat file, misal: PO Customer, Kontrak, dll.', max_length=255, verbose_name='Description')),
                ('job_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='sales.joborder', verbose_name='Job Order')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='joborder_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Order Attachment',
                'verbose_name_plural': 'Job Order Attachments',
                'ordering': ['-created_at'],
            },
        ),
    ]
