# Generated by Django 5.2.6 on 2025-12-13 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0041_joborderattachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='category',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='freight_order',
        ),
        migrations.AddField(
            model_name='invoice',
            name='job_order',
            field=models.ForeignKey(null=False,blank=False, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='sales.joborder'),
        ),
    ]
