# Generated by Django 5.2.6 on 2025-12-14 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0042_remove_invoice_category_remove_invoice_freight_order_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='invoiceline',
            table='sales_invoice_lines',
        ),
    ]
