# Generated by Django 5.2.6 on 2025-12-14 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0043_alter_invoiceline_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='job_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='sales.joborder'),
        ),
    ]
