# Generated by Django 5.2.6 on 2025-12-14 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0044_alter_invoice_job_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('UNPAID', 'Unpaid'), ('PAID', 'Paid')], default='DRAFT', max_length=20),
        ),
    ]
