# Generated by Django 5.2.6 on 2025-12-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0045_alter_invoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='joborder',
            name='is_invoiced',
            field=models.BooleanField(default=False, help_text='Sudah dibuat invoice'),
        ),
    ]
