# Generated by Django 5.2.6 on 2025-12-14 09:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0046_joborder_is_invoiced'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoiceline',
            options={'ordering': ['id']},
        ),
        migrations.RenameField(
            model_name='invoiceline',
            old_name='unit_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='payment_term',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='invoiceline',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='invoiceline',
            name='uom',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='notes_customer',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='notes_internal',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.CharField(editable=False, help_text='Nomor invoice (auto dari NumberSequence).', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='description',
            field=models.TextField(),
        ),
    ]
