# Generated by Django 5.2.6 on 2025-12-15 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_tax_code'),
        ('sales', '0048_alter_invoice_options_alter_invoiceline_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.tax'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='taxes',
            field=models.ManyToManyField(blank=True, related_name='invoice_lines', to='core.tax'),
        ),
    ]
