# Generated by Django 5.2.6 on 2025-12-15 18:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0049_invoice_tax_invoiceline_taxes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceline',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=18),
        ),
    ]
