# Generated by Django 5.2.6 on 2025-12-16 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0011_partner_bank_account_name'),
        ('sales', '0051_alter_invoice_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_invoices', to='partners.customer', verbose_name='Customer'),
        ),
    ]
