# Generated by Django 5.2.6 on 2025-12-16 11:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0052_alter_invoice_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='apply_pph',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='pph_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AddField(
            model_name='invoice',
            name='pph_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
    ]
