# Generated by Django 5.2.6 on 2025-12-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0053_invoice_apply_pph_invoice_pph_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joborder',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('PENDING', 'Pending'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], db_index=True, default='IN_PROGRESS', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('PAID', 'Paid')], db_index=True, default='DRAFT', max_length=20),
        ),
    ]
