# Generated by Django 5.2.6 on 2025-12-28 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0012_vendor'),
        ('sales', '0055_invoice_journal'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcost',
            name='category',
            field=models.CharField(choices=[('VENDOR', 'Vendor Cost'), ('MOBILIZATION', 'Mobilization'), ('LABOUR', 'Labour'), ('DOCUMENT', 'Document'), ('MISC', 'Misc')], db_index=True, default='VENDOR', max_length=20),
        ),
        migrations.AddField(
            model_name='jobcost',
            name='internal_note',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='jobcost',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='partners.vendor'),
        ),
    ]
