# Generated by Django 5.2.6 on 2025-12-29 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_accountingsettings_default_pph_account'),
        ('sales', '0056_jobcost_category_jobcost_internal_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='journal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='accounting.journal'),
        ),
    ]
