# Generated by Django 5.2.6 on 2025-12-29 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_accountingsettings_default_pph_account'),
        ('sales', '0057_alter_invoice_journal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='journal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='accounting.journal'),
        ),
    ]
