# Generated by Django 5.2.6 on 2025-12-29 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0058_alter_invoice_journal'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='uom',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
