# Generated by Django 5.2.6 on 2025-12-29 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0059_invoiceline_uom'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-invoice_date', '-id'], 'permissions': [('confirm_invoice', 'Can confirm invoice'), ('receive_payment', 'Can create/post receipt for invoice')]},
        ),
    ]
