# Generated by Django 5.2.6 on 2026-01-04 13:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0060_alter_invoice_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=Decimal('1.000000'), help_text='Kurs ke IDR. Wajib diisi jika currency bukan IDR.', max_digits=18),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_idr',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total dalam IDR (final, dipakai report/journal).', max_digits=18),
        ),
    ]
