# Generated by Django 5.2.6 on 2026-01-04 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_exchangerate'),
        ('sales', '0062_invoice_confirmed_at_invoice_confirmed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.service'),
        ),
    ]
