# Generated by Django 5.2.6 on 2026-01-04 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_joborder_complete_journal_alter_jobcost_cost_type'),
        ('sales', '0063_invoiceline_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='job_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='job.joborder'),
        ),
    ]
