# Generated by Django 5.2.6 on 2026-01-23 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_coresetting_text_value'),
        ('sales', '0064_alter_invoice_job_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freightorder',
            name='sales_service',
        ),
        migrations.RemoveField(
            model_name='freightquotation',
            name='sales_service',
        ),
        migrations.AddField(
            model_name='freightorder',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='freight_orders', to='core.service'),
        ),
        migrations.AddField(
            model_name='freightquotation',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='freight_quotations_service', to='core.service'),
        ),
    ]
