# Generated by Django 5.2.6 on 2026-01-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0065_remove_freightorder_sales_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freightquotation',
            name='delivery',
            field=models.CharField(blank=True, help_text='Delivery Location.', max_length=255, verbose_name='Delivery'),
        ),
        migrations.AddField(
            model_name='freightquotation',
            name='pickup',
            field=models.CharField(blank=True, help_text='Pickup Location.', max_length=255, verbose_name='Pick Up'),
        ),
    ]
