# Generated by Django 5.2.6 on 2026-01-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0066_freightquotation_delivery_freightquotation_pickup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freightquotation',
            name='delivery',
            field=models.TextField(blank=True, help_text='Delivery Location.', max_length=255, verbose_name='Delivery'),
        ),
        migrations.AlterField(
            model_name='freightquotation',
            name='pickup',
            field=models.TextField(blank=True, help_text='Pickup Location.', max_length=255, verbose_name='Pick Up'),
        ),
    ]
