# Generated by Django 5.2.6 on 2026-02-06 23:24

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_userprofile'),
        ('sales', '0067_alter_freightquotation_delivery_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_signature_source', models.CharField(choices=[('SALES_USER', 'Sales User'), ('SPECIFIC_USER', 'Specific User')], default='SALES_USER', max_length=20)),
                ('joborder_signature_source', models.CharField(choices=[('SALES_USER', 'Sales User'), ('SPECIFIC_USER', 'Specific User')], default='SALES_USER', max_length=20)),
                ('quotation_valid_days', models.PositiveIntegerField(default=0, help_text='0 = tidak pakai masa berlaku (opsional).')),
                ('sales_fee_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fee dalam persen, contoh: 2.50', max_digits=8)),
                ('customer_note', models.TextField(blank=True, default='')),
                ('term_conditions', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_currency', models.ForeignKey(blank=True, help_text='Default currency untuk quotation / job order', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.currency')),
                ('joborder_signature_user', models.ForeignKey(blank=True, help_text='Dipakai jika source = SPECIFIC_USER', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('quotation_signature_user', models.ForeignKey(blank=True, help_text='Dipakai jika source = SPECIFIC_USER', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sales Config',
                'verbose_name_plural': 'Sales Config',
            },
        ),
    ]
