# Generated by Django 5.2.6 on 2026-02-10 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0068_salesconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

operations = [
    migrations.AddField(
        model_name='salesconfig',
        name='service_order_signature_source',
        field=models.CharField(
            choices=[('SALES_USER', 'Sales User'), ('SPECIFIC_USER', 'Specific User')],
            default='SALES_USER',
            max_length=20
        ),
    ),
    migrations.AddField(
        model_name='salesconfig',
        name='service_order_signature_user',
        field=models.ForeignKey(
            blank=True,
            help_text='Dipakai jika source = SPECIFIC_USER',
            null=True,
            on_delete=django.db.models.deletion.SET_NULL,
            related_name='+',
            to=settings.AUTH_USER_MODEL,
        ),
    ),
    migrations.AddField(
        model_name='salesconfig',
        name='service_order_term_conditions',
        field=models.TextField(blank=True, default=''),
    ),

    # 🔥 INI YANG PENTING
    migrations.RenameField(
        model_name='salesconfig',
        old_name='vendor_note_default',
        new_name='vendor_note',
    ),
]
