# Generated by Django 5.2.6 on 2026-02-10 20:30

import django.db.models.deletion
import django_summernote.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0069_salesconfig_service_order_signature_source_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salesconfig',
            name='service_order_signature_source',
            field=models.CharField(choices=[('SALES_USER', 'Sales User'), ('SPECIFIC_USER', 'Specific User')], default='SALES_USER', max_length=20),
        ),
        migrations.AddField(
            model_name='salesconfig',
            name='service_order_signature_user',
            field=models.ForeignKey(blank=True, help_text='Dipakai jika source = SPECIFIC_USER', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesconfig',
            name='service_order_term_conditions',
            field=django_summernote.fields.SummernoteTextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='salesconfig',
            name='vendor_note',
            field=django_summernote.fields.SummernoteTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='salesconfig',
            name='customer_note',
            field=django_summernote.fields.SummernoteTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='salesconfig',
            name='term_conditions',
            field=django_summernote.fields.SummernoteTextField(blank=True, default=''),
        ),
    ]
