# Generated by Django 5.2.6 on 2026-02-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0070_salesconfig_service_order_signature_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesconfig',
            name='bank_transfer_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
