# Generated by Django 5.2.6 on 2026-02-22 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0071_salesconfig_bank_transfer_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesconfig',
            name='default_payment_term_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
