# Generated by Django 5.2.6 on 2026-02-22 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_userprofile'),
        ('sales', '0072_salesconfig_default_payment_term_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesconfig',
            name='default_payment_term_days',
        ),
        migrations.AddField(
            model_name='salesconfig',
            name='default_payment_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_default_configs', to='core.paymentterm'),
        ),
    ]
