# Generated by Django 5.2.6 on 2026-02-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_userprofile'),
        ('sales', '0073_remove_salesconfig_default_payment_term_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('DP', 'Down Payment'), ('FINAL', 'Final Invoice'), ('REGULAR', 'Regular Invoice')], db_index=True, default='REGULAR', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('PARTIAL', 'Partial'), ('PAID', 'Paid')], db_index=True, default='DRAFT', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='invoiceline',
            constraint=models.UniqueConstraint(condition=models.Q(('invoice_type', 'DP')), fields=('job_order',), name='unique_dp_per_job'),
        ),
    ]
