# Generated by Django 5.2.6 on 2026-02-24 10:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0017_accountingsettings_auto_create_job_costing_journal_and_more'),
        ('core', '0029_userprofile'),
        ('job', '0044_alter_joborder_job_source'),
        ('partners', '0013_alter_partner_address_alter_partner_address_line1_and_more'),
        ('sales', '0074_invoice_invoice_type_alter_invoice_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='invoiceline',
            name='unique_dp_per_job',
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('invoice_type', 'DP')), fields=('job_order',), name='unique_dp_per_job'),
        ),
    ]
