# Generated by Django 5.2.6 on 2026-02-26 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0075_remove_invoiceline_unique_dp_per_job_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceline',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='invoiceline',
            name='service',
        ),
        migrations.RemoveField(
            model_name='invoiceline',
            name='taxes',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='InvoiceLine',
        ),
    ]
